"""headless.hy の公開面の型(Python の読み手 = 検)。defk は Program を返す。"""

from doeff import Program

HEADLESS_BACKEND_KIND: str
EVENT_SESSION_INTERRUPTED: str
EVENT_SESSION_TURN_ENDED: str
EVENT_SESSION_INJECTED: str
SEND_MODE_TURN: str
SEND_MODE_INTERRUPT: str
SEND_MODES: frozenset[str]

def headless_events_path(events_root: str, session_id: str) -> str: ...
def headless_launch_session(params: dict) -> Program: ...
def headless_send_program(session_id: str, message: str, awaiting: bool) -> Program: ...
def headless_inject_program(session_id: str, message: str) -> Program: ...
def headless_interrupt_program(session_id: str) -> Program: ...
def headless_cancel_program(session_id: str) -> Program: ...
def headless_cleanup_program(session_id: str) -> Program: ...
def headless_capture_program(session_id: str, lines: int) -> Program: ...
def headless_monitor_cycle() -> Program: ...
def recover_headless_rows() -> Program: ...
def stop_headless_rows(reason: str) -> Program: ...
