"""store.hy の公開面の型(Python の読み手 = 検)。部分的な stub: 検が触る StoreActor だけ。"""

from collections.abc import Callable

class StoreActor:
    def __init__(self, db_path: str) -> None: ...
    def submit(self, op: Callable[[object], object]) -> object: ...
    def close(self) -> None: ...
