"""table.hy の公開面の型 — 書き換えない表 Table・その書き TableWrite・下書き TableDraft と、作る口 table_of・draft_of(agora-redesign #2254)。

table.hy は Hy の module で、型の宣言が無いと pyright は使い手の Table を Unknown として読み、表を欄や引数に持つ所の型が全部
Unknown に引きずられる(書き手に直せない赤)。口の形は table.hy と同じ — 片方だけ変えない(検 tests/test_table_static_types.py)。
"""

from dataclasses import dataclass
from typing import Generic, TypeVar

V = TypeVar("V")

COMPACT_RATIO: int
MIN_DELTA: int

@dataclass(frozen=True)
class TableWrite(Generic[V]):
    key: str
    value: V | None

class Table(Generic[V]):
    def __init__(self, base: dict[str, V], delta: dict[str, V], removed: frozenset[str]) -> None: ...
    def row(self, key: str) -> V | None: ...
    def keys(self) -> tuple[str, ...]: ...
    def rows(self) -> tuple[V, ...]: ...
    def items(self) -> tuple[tuple[str, V], ...]: ...
    def size(self) -> int: ...
    def with_writes(self, writes: tuple[TableWrite[V], ...]) -> Table[V]: ...
    def __eq__(self, other: object) -> bool: ...
    def __reduce__(self) -> tuple[type[Table[V]], tuple[dict[str, V], dict[str, V], frozenset[str]]]: ...

class TableDraft(Generic[V]):
    def __init__(self, table: Table[V]) -> None: ...
    def row(self, key: str) -> V | None: ...
    def keys(self) -> tuple[str, ...]: ...
    def rows(self) -> tuple[V, ...]: ...
    def put(self, key: str, value: V) -> None: ...
    def remove(self, key: str) -> None: ...
    def freeze(self) -> Table[V]: ...

def table_of(rows: tuple[TableWrite[V], ...]) -> Table[V]: ...
def draft_of(table: Table[V]) -> TableDraft[V]: ...
