"""typecheck_handlers.hy の公開面の型(柵 3 — 果たす 2 つの家)。

関数だけを宣言する(共通の品質検査の同名 stub の照合は関数の面だけを読む)。
"""

from doeff import Program

def type_checks_off(program: Program) -> Program: ...
def type_checks_on(program: Program) -> Program: ...
def run_with_type_checks(program: Program) -> object: ...
def run_without_type_checks(program: Program) -> object: ...
