"""
doeff-conductor: Multi-agent workflow orchestration.

This package provides a unified orchestration layer for multi-agent workflows:

- Issue-driven agent workflows
- Git workspace management
- Multi-agent DAG execution
- Full CLI for monitoring and control
"""

from doeff_conductor.api import ConductorAPI
from doeff_conductor.effects import (
    BLOCKER_FINDING,
    CALIBRATION_SAMPLE_BUDGET_KEY,
    DEFAULT_REVIEW_ROUTE_TABLE,
    REVIEW_VERDICT_RESULT_SCHEMA,
    TIER1_REVIEW_BUDGET_KEY,
    TIER2_ESCALATION_BUDGET_KEY,
    Agent,
    AgentAttemptExhaustedError,
    AgentCall,
    AgentDeadlineExceededError,
    AgentEffect,
    AgentTask,
    AgentValidationErrorKind,
    AgentValidationFailure,
    Commit,
    ConductorEffectBase,
    CreateIssue,
    CreatePR,
    CreateWorkspace,
    DefaultReviewRouter,
    DeleteWorkspace,
    DurableReviewBudget,
    Exec,
    GateCall,
    GetIssue,
    ListIssues,
    MergeCall,
    MergePR,
    MergeWorkspaces,
    OpenGate,
    OpenGateReason,
    Push,
    RandomCall,
    RemainingReviewBudget,
    ResolveIssue,
    ReviewerAgentLost,
    ReviewEscalationReason,
    ReviewEscalationTerminal,
    ReviewFinding,
    ReviewItem,
    ReviewRoutingResult,
    ReviewSeverity,
    ReviewStakes,
    ReviewStakesLevel,
    ReviewVerdict,
    ReviewVerdictArtifact,
    ReviewVerdictTerminal,
    TimeCall,
    WorkspaceCall,
    route_review_item,
    run_review_routing_demo,
)
from doeff_conductor.exceptions import (
    AgentError,
    AgentTimeoutError,
    ConductorError,
    ConductorStateWarning,
    GitCommandError,
    IssueAlreadyExistsError,
    IssueFileCorruptError,
    IssueNotFoundError,
    JournalCorruptionError,
    PRError,
    WorkspaceError,
)
from doeff_conductor.handlers import (
    AgentBackend,
    AgentdAgentBackend,
    AgentHandler,
    ExecHandler,
    GitHandler,
    IssueHandler,
    JournaledAgentHandler,
    JournaledWorkflowEffectHandler,
    MockConductorRuntime,
    WorkspaceHandler,
    default_scheduled_handlers,
    make_async_scheduled_handler,
    make_blocking_scheduled_handler,
    make_blocking_scheduled_handler_with_store,
    make_scheduled_handler,
    make_scheduled_handler_with_store,
    mock_handlers,
    production_handlers,
)
from doeff_conductor.replay_keying import (
    ResolvedIdentity,
    agent_cache_key,
    longest_valid_prefix,
    node_identity_fingerprint,
    resolved_identity_fingerprint,
    workflow_effect_cache_key,
)
from doeff_conductor.templates import (
    basic_pr,
    enforced_pr,
    get_available_templates,
    get_template,
    get_template_source,
    is_template,
    multi_agent,
    reviewed_pr,
)
from doeff_conductor.types import (
    AgentRef,
    ExecResult,
    Issue,
    IssueStatus,
    MergeConflict,
    MergeStatus,
    MergeStrategy,
    MergeWorkspacesResult,
    PRHandle,
    WorkflowHandle,
    WorkflowStatus,
    Workspace,
)
