from collections.abc import Callable as _CallableT
from collections.abc import Generator, Sequence
from typing import Any, Generic, Literal, Protocol, SupportsIndex, overload

from typing_extensions import Never, Self, TypeVar

_T = TypeVar("_T")
_T_co = TypeVar("_T_co", covariant=True)
_E_co = TypeVar("_E_co", covariant=True, default=Any)
# The answer type of an effect. Bare ``EffectBase`` (a handler's ``effect: EffectBase``,
# "any effect") means ``EffectBase[Any]``, so code written before effects carried an
# answer type stays fully known under strict checking.
_Answer = TypeVar("_Answer", default=Any)

# Static typing of effects and programs (runtime half: src/typing_support.rs).
#
# - ``EffectBase[T]``: an effect whose handler answers with a T. ``x = yield from eff``
#   gives ``x: T`` (``yield eff`` still works and gives Any). T is invariant so that
#   ``doeff.typed_resume(effect, k, value)`` rejects an answer of the wrong type.
# - Program nodes are ``yield from``-able the same way: ``Expand[T, E]`` is the program a
#   ``@do`` function returns — T its result, E the union of effects its body yields.

class _ProgramLike(Protocol[_T_co]):
    def __iter__(self) -> Generator[Any, Any, _T_co]: ...

# --- VM ---

class UnhandledEffect(RuntimeError): ...  # noqa: N818 - public or fixture exception name is intentionally stable

class PyVM:
    def __init__(self) -> None: ...
    def run(self, program: Any) -> Any: ...
    def arena_stats(self) -> tuple[int, int, int, int]: ...
    def step_count(self) -> int: ...

# --- Continuation ---

class K:
    def __repr__(self) -> str: ...

# --- Callable / Stream ---

class Callable:
    def __init__(self, callable_: Any) -> None: ...

class HandlerSpec:
    """What the VM captures when it installs a handler (``doeff_vm._effect_types.handler_spec``)."""

    def __init__(
        self,
        effect_types: tuple[type, ...] | None,
        generator_function: object,
        tail_resume_lines: Sequence[int],
        passed: tuple[tuple[type, ...], tuple[type, ...]] | None,
    ) -> None: ...
    @property
    def effect_types(self) -> tuple[type, ...] | None: ...
    @property
    def generator_function(self) -> object: ...
    @property
    def tail_resume_lines(self) -> tuple[int, ...]: ...
    @property
    def passed(self) -> tuple[tuple[type, ...], tuple[type, ...]] | None: ...

class IRStream:
    def __init__(self, generator: Any, tail_resume_lines: Any | None = None) -> None: ...

# --- EffectBase ---

class EffectBase(Generic[_Answer]):
    def __init__(self, *_args: Any, **_kwargs: Any) -> None: ...
    def __iter__(self) -> Generator[Self, Any, _Answer]: ...
    def __reduce_ex__(self, protocol: SupportsIndex) -> tuple[Any, ...]: ...

# --- Result types ---

class Ok(Generic[_T]):
    value: _T
    def __init__(self, value: _T) -> None: ...
    def is_ok(self) -> bool: ...
    def is_err(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __reduce__(self) -> tuple[Any, tuple[Any]]: ...

class Err:
    error: Any
    captured_traceback: Any
    def __init__(self, error: Any, captured_traceback: Any | None = None) -> None: ...
    def is_ok(self) -> bool: ...
    def is_err(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __reduce__(self) -> tuple[Any, tuple[Any, Any]]: ...

# --- DoExpr pyclasses ---

class Pure(Generic[_T_co]):
    @property
    def value(self) -> _T_co: ...
    def __init__(self, value: _T_co) -> None: ...
    def __iter__(self) -> Generator[Never, Any, _T_co]: ...
    def __repr__(self) -> str: ...

class Perform(Generic[_T]):
    effect: EffectBase[_T]
    def __init__(self, effect: EffectBase[_T]) -> None: ...
    def __iter__(self) -> Generator[Self, Any, _T]: ...
    def __repr__(self) -> str: ...

class Resume:
    continuation: K
    value: Any
    def __init__(self, k: K, value: Any) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Generator[Self, Any, Any]: ...

class Transfer:
    continuation: K
    value: Any
    def __init__(self, k: K, value: Any) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Generator[Self, Any, Any]: ...

class Apply:
    f: Any
    args: Any
    def __init__(self, f: Any, args: Any) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Generator[Self, Any, Any]: ...

class Expand(Generic[_T_co, _E_co]):
    """A program: T = its result, E = the effects its body yields (``@do`` fills both)."""

    expr: Any
    def __init__(self, expr: Any) -> None: ...
    def __iter__(self) -> Generator[_E_co, Any, _T_co]: ...
    def __repr__(self) -> str: ...

class DoFunction:
    """A ``@do`` definition: the undecorated function, its tail-resume lines, and whether
    its body yields (a call to one that does not performs nothing)."""

    function: _CallableT[..., Any]
    tail_resume_lines: list[int]
    yields: bool
    def __init__(
        self, function: _CallableT[..., Any], tail_resume_lines: list[int], yields: bool
    ) -> None: ...
    def make_call(self, args: tuple[Any, ...], kwargs: dict[str, Any]) -> Call[Any, Any]:
        """The ``Call`` of this definition — what the ``@do`` wrapper builds per call."""
        ...
    def __repr__(self) -> str: ...

class Call(Expand[_T_co, _E_co]):
    """The program a ``@do`` function returns: call ``function.function(*args, **kwargs)``."""

    function: DoFunction
    args: tuple[Any, ...]
    kwargs: dict[str, Any]
    def __init__(
        self, function: DoFunction, args: tuple[Any, ...], kwargs: dict[str, Any]
    ) -> None: ...

class BindOpener:
    """What ``outcomes.open_bind`` is: a no-``absent`` bind of a ``Call`` whose definition
    does not yield is called in place (``Pure(answer)``, or ``generator_program(gen)`` for a
    generator answer); every other bind goes to ``fallback(expr[, absent])``."""

    fallback: _CallableT[..., Any]
    generator_program: _CallableT[[Generator[Any, Any, Any]], Any]
    def __init__(
        self, fallback: _CallableT[..., Any], generator_program: _CallableT[[Generator[Any, Any, Any]], Any]
    ) -> None: ...
    def __call__(self, expr: Any, absent: _CallableT[[], Any] | None = None) -> Any: ...
    def __repr__(self) -> str: ...

class Pass:
    effect: Any
    continuation: K
    def __init__(self, effect: Any, k: K) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Generator[Self, Any, Any]: ...

class WithHandler(Generic[_T_co]):
    handler: Any
    body: Any
    @overload
    def __init__(self: WithHandler[_T], handler: _CallableT[..., object], body: _ProgramLike[_T]) -> None: ...
    @overload
    def __init__(self: WithHandler[Any], handler: _CallableT[..., object], body: object) -> None: ...
    def __iter__(self) -> Generator[Any, Any, _T_co]: ...
    def __repr__(self) -> str: ...

class ResumeThrow:
    continuation: K
    exception: Any
    def __init__(self, k: K, exception: Any) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Generator[Self, Any, Any]: ...

class TransferThrow:
    continuation: K
    exception: Any
    def __init__(self, k: K, exception: Any) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Generator[Self, Any, Any]: ...

class WithObserve(Generic[_T_co]):
    observer: Any
    body: Any
    @overload
    def __init__(self: WithObserve[_T], observer: Any, body: _ProgramLike[_T]) -> None: ...
    @overload
    def __init__(self: WithObserve[Any], observer: Any, body: object) -> None: ...
    def __iter__(self) -> Generator[Any, Any, _T_co]: ...
    def __repr__(self) -> str: ...

class WithBoundaries(Generic[_T_co]):
    """Install a captured boundary stack (innermost first) around body in one VM step (#3149)."""

    boundaries: Sequence[tuple[Literal["handler", "observer"], Any]]
    body: Any
    @overload
    def __init__(
        self: WithBoundaries[_T],
        boundaries: Sequence[tuple[Literal["handler", "observer"], Any]],
        body: _ProgramLike[_T],
    ) -> None: ...
    @overload
    def __init__(
        self: WithBoundaries[Any],
        boundaries: Sequence[tuple[Literal["handler", "observer"], Any]],
        body: object,
    ) -> None: ...
    def __iter__(self) -> Generator[Any, Any, _T_co]: ...
    def __repr__(self) -> str: ...

class GetTraceback:
    continuation: K
    def __init__(self, k: K) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Generator[Self, Any, Any]: ...

class GetExecutionContext:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Generator[Self, Any, Any]: ...

class GetHandlers:
    continuation: K
    def __init__(self, k: K) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Generator[Self, Any, Any]: ...

class GetBoundaries:
    continuation: K
    def __init__(self, k: K) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Generator[Self, Any, Any]: ...

class GetOuterHandlers:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Generator[Self, Any, Any]: ...

class TailEval:
    expr: Any
    def __init__(self, expr: Any) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Generator[Self, Any, Any]: ...

def vm_live_counts() -> tuple[int, int, int]: ...
