from __future__ import annotations

from typing import Any, Generic, TypeVar

_T = TypeVar("_T")

# --- VM ---

class PyVM:
    def __init__(self) -> None: ...
    def run(self, program: Any) -> Any: ...

# --- Continuation ---

class K:
    def __repr__(self) -> str: ...

# --- Callable / Stream ---

class Callable:
    def __init__(self, callable: Any) -> None: ...

class IRStream:
    def __init__(self, generator: Any) -> None: ...

# --- EffectBase ---

class EffectBase:
    def __init__(self, *_args: Any, **_kwargs: Any) -> None: ...
    def __reduce_ex__(self, protocol: int) -> tuple[Any, ...]: ...

# --- Result types ---

class Ok(Generic[_T]):
    value: _T
    def __init__(self, value: _T) -> None: ...
    def is_ok(self) -> bool: ...
    def is_err(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __reduce__(self) -> tuple[Any, tuple[Any]]: ...

class Err:
    error: Any
    captured_traceback: Any
    def __init__(self, error: Any, captured_traceback: Any | None = None) -> None: ...
    def is_ok(self) -> bool: ...
    def is_err(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __reduce__(self) -> tuple[Any, tuple[Any, Any]]: ...

# --- DoExpr pyclasses ---

class Pure:
    value: Any
    def __init__(self, value: Any) -> None: ...
    def __repr__(self) -> str: ...

class Perform:
    effect: Any
    def __init__(self, effect: Any) -> None: ...
    def __repr__(self) -> str: ...

class Resume:
    continuation: K
    value: Any
    def __init__(self, k: K, value: Any) -> None: ...
    def __repr__(self) -> str: ...

class Transfer:
    continuation: K
    value: Any
    def __init__(self, k: K, value: Any) -> None: ...
    def __repr__(self) -> str: ...

class Apply:
    f: Any
    args: Any
    def __init__(self, f: Any, args: Any) -> None: ...
    def __repr__(self) -> str: ...

class Expand:
    expr: Any
    def __init__(self, expr: Any) -> None: ...
    def __repr__(self) -> str: ...

class Pass:
    effect: Any
    continuation: K
    def __init__(self, effect: Any, k: K) -> None: ...
    def __repr__(self) -> str: ...

class WithHandler:
    handler: Any
    body: Any
    def __init__(self, handler: Any, body: Any) -> None: ...
    def __repr__(self) -> str: ...

class ResumeThrow:
    continuation: K
    exception: Any
    def __init__(self, k: K, exception: Any) -> None: ...
    def __repr__(self) -> str: ...

class TransferThrow:
    continuation: K
    exception: Any
    def __init__(self, k: K, exception: Any) -> None: ...
    def __repr__(self) -> str: ...

class WithObserve:
    observer: Any
    body: Any
    def __init__(self, observer: Any, body: Any) -> None: ...
    def __repr__(self) -> str: ...

class GetTraceback:
    continuation: K
    def __init__(self, k: K) -> None: ...
    def __repr__(self) -> str: ...

class GetExecutionContext:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

class GetHandlers:
    continuation: K
    def __init__(self, k: K) -> None: ...
    def __repr__(self) -> str: ...
