# doeff_hy.static_stub が作った型の宣言 — 手で直さない(元 = job_model.hy・作り直し = python -m doeff_hy.static_stub --write <この .pyi の隣の .hy>)

from dataclasses import dataclass as dataclass
from dataclasses import field as field
from enum import Enum as Enum
from functools import cached_property as cached_property

@dataclass(frozen=True)
class JobSpec:
    name: str
    entry: str
    args: tuple[str, ...]
    revision: str
    once: bool = False
    placement: int | None = ...
    handoff: bool = ...
    ready_instance: str | None = ...
    handoff_abandoned: bool = ...
    retired_ms: int | None = ...
    retired_limit: int | None = ...
    detached: bool = ...
    runtime_env: str | None = None
    env_key: str | None = ...
    program: str | None = ...
    environ: tuple[tuple[str, str], ...] = ...
    keep_when_cut_off: bool = ...
    hold_version: bool = ...
    versions: tuple[tuple[str, str], ...] | None = ...

    def __post_init__(self) -> None:
        ...

    def fingerprint(self) -> str:
        ...

class JobPhase(Enum):
    PREPARING = 'preparing'
    CODE_FAILED = 'code-failed'
    STARTING = 'starting'
    PROBING = 'probing'
    BACKOFF = 'backoff'
    RUNNING = 'running'
    STOPPING = 'stopping'
    STOP_UNCONFIRMED = 'stop-unconfirmed'
    PROBE_FAILED = 'probe-failed'
    ENV_FAILED = 'env-failed'
    HANDOFF_ABANDONED = 'handoff-abandoned'
    FINISHED = 'finished'
    STOPPED = 'stopped'
