"""hy.models の型(型検査のための宣言 — 実行時は hy/models.py を読む・doeff-hy が配る部分の stub・agora-redesign #2313)。

Hy の展開は keyword の literal と quote した form を `hy.models.Keyword("x")`・`hy.models.Expression([...])` に compile し、
doeff-hy-check はそれを読む module に `import hy.models` を置く。hy は型の宣言を持たないので、その import に strict の
reportMissingTypeStubs が出ていた。ここで model の型を宣言する。

Sequence の要素は object とする — reader と quote が作る列の要素は model だが、macro が組む列には model でない値(str・None)も
入り(as_model が後で包む)、構築子は何の値も受ける。要素を model として使う所は isinstance で絞る。
"""

from collections.abc import Iterable, Iterator, Mapping
from contextlib import AbstractContextManager
from typing import ClassVar, Self, SupportsIndex, TypeVar, overload

_V = TypeVar("_V")
_D = TypeVar("_D")

PRETTY: bool

def pretty(pretty: bool = True) -> AbstractContextManager[None]: ...

class Object:
    """Hy の model(form)の抽象の基底。位置は 1 始まり・両端を含む(無ければ 1)。"""

    properties: ClassVar[list[str]]
    start_line: int
    start_column: int
    end_line: int
    end_column: int
    def replace(self, other: Object, recursive: bool = False) -> Self: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

def as_model(x: object) -> Object: ...
def replace_hy_obj(obj: object, other: Object) -> Object: ...
def repr_indent(obj: object) -> str: ...
def is_unpack(kind: str, x: object) -> bool: ...

class String(Object, str):
    __match_args__ = ("_as_str",)
    brackets: str | None
    def __new__(cls, s: str = ..., brackets: str | None = None) -> Self: ...
    def __add__(self, other: str) -> Self: ...
    @property
    def _as_str(self) -> str: ...

class Bytes(Object, bytes):
    __match_args__ = ("_as_bytes",)
    @property
    def _as_bytes(self) -> bytes: ...

class Symbol(Object, str):
    __match_args__ = ("_as_str",)
    def __new__(cls, s: object, from_parser: bool = False) -> Self: ...
    @property
    def _as_str(self) -> str: ...

class Keyword(Object):
    __match_args__ = ("name",)
    name: str
    def __init__(self, value: object, from_parser: bool = False) -> None: ...
    def __lt__(self, other: Keyword) -> bool: ...
    def __le__(self, other: Keyword) -> bool: ...
    def __gt__(self, other: Keyword) -> bool: ...
    def __ge__(self, other: Keyword) -> bool: ...
    def __bool__(self) -> bool: ...
    @overload
    def __call__(self, data: Mapping[str, _V]) -> _V: ...
    @overload
    def __call__(self, data: Mapping[str, _V], default: _D) -> _V | _D: ...

class Integer(Object, int):
    __match_args__ = ("_as_int",)
    def __new__(cls, number: int | str) -> Self: ...
    @property
    def _as_int(self) -> int: ...

class Float(Object, float):
    __match_args__ = ("_as_float",)
    def __new__(cls, num: float | str) -> Self: ...
    @property
    def _as_float(self) -> float: ...

class Complex(Object, complex):
    __match_args__ = ("real", "imag")
    def __new__(cls, real: complex | str, imag: float = 0) -> Self: ...

class Sequence(Object, tuple[object, ...]):
    """列の形の model の抽象の基底(tuple のように添字・反復・+ ができ、要素は書き換えられない)。"""

    def __new__(cls, iterable: Iterable[object] = ...) -> Self: ...
    def replace(self, other: Object, recursive: bool = True) -> Self: ...
    # + は左の型の列を返す(list の右も受ける — hy/models.py の Sequence.__add__)。
    def __add__(self, other: tuple[object, ...] | list[object]) -> Self: ...
    @overload
    def __getitem__(self, item: SupportsIndex) -> object: ...
    @overload
    def __getitem__(self, item: slice) -> Self: ...

class FComponent(Sequence):
    conversion: str | None
    expression: str | None
    is_tstring: bool
    def __new__(
        cls,
        s: Iterable[object] = ...,
        conversion: str | None = None,
        expression: str | None = None,
        is_tstring: bool = False,
    ) -> Self: ...

class FString(Sequence):
    brackets: str | None
    is_tstring: bool
    def __new__(cls, s: Iterable[object] = ..., brackets: str | None = None, is_tstring: bool = False) -> Self: ...

class List(Sequence): ...

class Dict(Sequence):
    def keys(self) -> list[object]: ...
    def values(self) -> list[object]: ...
    def items(self) -> list[tuple[object, object]]: ...

class Expression(Sequence): ...
class Set(Sequence): ...
class Tuple(Sequence): ...

class Lazy(Object):
    """hy.read-many の答え — form を 1 つずつ読む反復子。"""

    def __init__(self, gen: Iterator[Object]) -> None: ...
    def __iter__(self) -> Iterator[Object]: ...
    def __next__(self) -> Object: ...
