"""
Basic PR workflow template.

Workflow: issue -> agent -> PR

The simplest workflow for implementing an issue:
1. Create a worktree for the issue
2. Run an agent to implement the issue
3. Commit, push, and create a PR
4. Mark the issue as resolved
"""

from doeff import EffectGenerator, do

from ..types import Issue, PRHandle

IMPLEMENT_SCHEMA = {
    "type": "object",
    "required": ["summary"],
    "properties": {
        "summary": {"type": "string"},
        "files_changed": {"type": "array", "items": {"type": "string"}},
    },
}


@do
def basic_pr(issue: Issue) -> EffectGenerator[PRHandle]:
    """Basic PR workflow: issue -> agent -> PR.

    Args:
        issue: The issue to implement

    Returns:
        PRHandle for the created PR
    """
    from ..effects import Agent, AgentTask, Commit, CreatePR, CreateWorkspace, Push, ResolveIssue

    # Step 1: Create isolated worktree
    env = yield CreateWorkspace(issue=issue)

    # Step 2: Run agent to implement the issue
    prompt = f"""
Implement the following issue:

# {issue.title}

{issue.body}

Please implement the changes needed to resolve this issue.
When done, make sure all changes are complete and working.
"""
    yield Agent(
        AgentTask(
            run_id=issue.id,
            node_id="implement",
            attempt=0,
            env=env,
            prompt=prompt,
            result_schema=IMPLEMENT_SCHEMA,
            verification_class="test-verifiable",
            agent_type="codex",
        )
    )

    # Step 3: Commit and push changes
    commit_msg = f"feat: {issue.title}\n\nResolves: {issue.id}"
    yield Commit(workspace=env, message=commit_msg)
    yield Push(workspace=env)

    # Step 4: Create PR
    pr = yield CreatePR(
        workspace=env,
        title=issue.title,
        body=f"""
## Summary

Implements {issue.id}: {issue.title}

## Changes

{issue.body}

---
Generated by doeff-conductor basic_pr template
""",
    )

    # Step 5: Resolve the issue
    yield ResolveIssue(issue=issue, pr_url=pr.url)

    return pr


__all__ = ["basic_pr"]
