"""
Enforced PR workflow template.

Workflow: issue -> agent -> test -> fix loop -> PR

A workflow with quality gates:
1. Create a worktree for the issue
2. Run an agent to implement the issue
3. Run tests
4. If tests fail, have the agent fix issues (up to N retries)
5. Create PR only if tests pass
"""


from typing import TYPE_CHECKING

from doeff import EffectGenerator, do

if TYPE_CHECKING:
    from ..types import Issue, PRHandle


@do
def enforced_pr(
    issue: Issue,
    max_retries: int = 3,
    test_command: str = "pytest",
) -> EffectGenerator[PRHandle]:
    """Enforced PR workflow: issue -> agent -> test -> fix loop -> PR.

    Args:
        issue: The issue to implement
        max_retries: Maximum fix attempts (default: 3)
        test_command: Command to run tests (default: pytest)

    Returns:
        PRHandle for the created PR

    Raises:
        RuntimeError: If tests still fail after max_retries
    """
    from ..effects import Commit, CreatePR, CreateWorktree, Push, ResolveIssue, RunAgent

    # Step 1: Create isolated worktree
    env = yield CreateWorktree(issue=issue)

    # Step 2: Run agent to implement the issue
    implement_prompt = f"""
Implement the following issue:

# {issue.title}

{issue.body}

Please implement the changes needed to resolve this issue.
Make sure to:
1. Write clean, well-documented code
2. Follow existing code patterns
3. Consider edge cases
"""
    yield RunAgent(env=env, prompt=implement_prompt)

    # Step 3: Test and fix loop
    tests_passed = False
    last_failure = ""

    for attempt in range(max_retries + 1):
        # Run tests via agent
        test_prompt = f"""
Run the test suite to verify the implementation:

```bash
{test_command}
```

Report the test results. If tests fail, describe what failed.
If tests pass, confirm that all tests are passing.
"""
        test_result = yield RunAgent(env=env, prompt=test_prompt)

        # Check if tests passed (simple heuristic)
        if "passed" in test_result.lower() and "failed" not in test_result.lower():
            tests_passed = True
            break

        if attempt < max_retries:
            # Have agent fix the issues
            fix_prompt = f"""
Tests failed with the following output:

{test_result}

Please fix the issues and make the tests pass.
Focus on:
1. Understanding the error messages
2. Making targeted fixes
3. Not breaking other functionality
"""
            yield RunAgent(env=env, prompt=fix_prompt)
            last_failure = test_result
        else:
            last_failure = test_result

    if not tests_passed:
        raise RuntimeError(
            f"Tests still failing after {max_retries} fix attempts:\n{last_failure}"
        )

    # Step 4: Commit and push changes
    commit_msg = f"feat: {issue.title}\n\nResolves: {issue.id}\n\nAll tests passing."
    yield Commit(env=env, message=commit_msg)
    yield Push(env=env)

    # Step 5: Create PR
    pr = yield CreatePR(
        env=env,
        title=issue.title,
        body=f"""
## Summary

Implements {issue.id}: {issue.title}

## Changes

{issue.body}

## Quality Checks

- All tests passing
- Verified via enforced_pr workflow with max {max_retries} retries

---
Generated by doeff-conductor enforced_pr template
""",
    )

    # Step 6: Resolve the issue
    yield ResolveIssue(issue=issue, pr_url=pr.url)

    return pr


__all__ = ["enforced_pr"]
