"""
Multi-agent PR workflow template.

Workflow: issue -> split agents -> merge -> PR

A workflow with separate implementation and test agents:
1. Create separate worktrees for implementation and tests
2. Run agents for implementation and test creation
3. Merge the branches
4. Run a review on the merged code
5. Create PR
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from doeff import EffectGenerator, do

if TYPE_CHECKING:
    from ..types import Issue, PRHandle, WorktreeEnv


@do
def _create_worktree(issue: Issue, suffix: str) -> EffectGenerator["WorktreeEnv"]:
    from ..effects import CreateWorktree

    return (yield CreateWorktree(issue=issue, suffix=suffix))


@do
def _run_agent(env: "WorktreeEnv", prompt: str, name: str) -> EffectGenerator[str]:
    from ..effects import RunAgent

    return (yield RunAgent(env=env, prompt=prompt, name=name))


@do
def _commit(env: "WorktreeEnv", message: str) -> EffectGenerator[str]:
    from ..effects import Commit

    return (yield Commit(env=env, message=message))


@do
def multi_agent(issue: Issue) -> EffectGenerator[PRHandle]:
    """Multi-agent PR workflow: issue -> parallel agents -> merge -> PR.

    Args:
        issue: The issue to implement

    Returns:
        PRHandle for the created PR
    """
    from ..effects import (
        Commit,
        CreatePR,
        MergeBranches,
        Push,
        ResolveIssue,
        RunAgent,
    )

    # Step 1: Create separate worktrees
    impl_env = yield _create_worktree(issue, "impl")
    test_env = yield _create_worktree(issue, "tests")

    # Step 2: Run implementation and test agents
    impl_prompt = f"""
Implement the following issue:

# {issue.title}

{issue.body}

Focus on implementing the core functionality.
Do NOT write tests - a separate agent will handle that.
"""

    test_prompt = f"""
Write tests for the following issue:

# {issue.title}

{issue.body}

Focus on writing comprehensive tests:
1. Unit tests for core functionality
2. Edge case tests
3. Integration tests if applicable

Do NOT implement the feature - just write the tests.
"""

    yield _run_agent(impl_env, impl_prompt, "implementer")
    yield _run_agent(test_env, test_prompt, "tester")

    # Step 3: Commit changes in branch worktrees
    yield _commit(impl_env, f"feat: implement {issue.title}")
    yield _commit(test_env, f"test: add tests for {issue.title}")

    # Step 4: Merge branches
    merged_env = yield MergeBranches(envs=(impl_env, test_env))

    # Step 5: Review and finalize
    review_prompt = f"""
Review the merged implementation and tests for:

# {issue.title}

{issue.body}

Check that:
1. Implementation is complete
2. Tests cover the implementation
3. Tests pass

If any fixes are needed, make them now.
"""
    yield RunAgent(env=merged_env, prompt=review_prompt, name="reviewer")

    # Step 6: Final commit and push
    yield Commit(env=merged_env, message=f"chore: finalize {issue.title}")
    yield Push(env=merged_env)

    # Step 7: Create PR
    pr = yield CreatePR(
        env=merged_env,
        title=issue.title,
        body=f"""
## Summary

Implements {issue.id}: {issue.title}

## Changes

{issue.body}

## Implementation Approach

This PR was created using the multi_agent workflow:
- **Implementer agent**: Focused on core functionality
- **Tester agent**: Focused on comprehensive test coverage
- **Reviewer agent**: Final integration and quality check

---
Generated by doeff-conductor multi_agent template
""",
    )

    # Step 8: Resolve the issue
    yield ResolveIssue(issue=issue, pr_url=pr.url)

    return pr


__all__ = ["multi_agent"]
