"""
Reviewed PR workflow template.

Workflow: issue -> agent -> review -> PR

A workflow with code review:
1. Create a worktree for the issue
2. Run an agent to implement the issue
3. Run a review agent to check the implementation
4. If issues found, have implementer fix them
5. Create PR once review passes
"""

from typing import TYPE_CHECKING

from doeff import EffectGenerator, do

if TYPE_CHECKING:
    from ..types import Issue, PRHandle


@do
def reviewed_pr(
    issue: "Issue",
    max_reviews: int = 2,
) -> "EffectGenerator[PRHandle]":
    """Reviewed PR workflow: issue -> agent -> review -> PR.

    Args:
        issue: The issue to implement
        max_reviews: Maximum review iterations (default: 2)

    Returns:
        PRHandle for the created PR
    """
    from ..effects import Commit, CreatePR, CreateWorktree, Push, ResolveIssue, RunAgent

    # Step 1: Create isolated worktree
    env = yield CreateWorktree(issue=issue)

    # Step 2: Run agent to implement the issue
    implement_prompt = f"""
Implement the following issue:

# {issue.title}

{issue.body}

Please implement the changes needed to resolve this issue.
Write clean, well-documented code following best practices.
"""
    yield RunAgent(env=env, prompt=implement_prompt, name="implementer")

    # Step 3: Review loop
    review_approved = False
    last_review = ""

    for iteration in range(max_reviews + 1):
        # Run review agent
        review_prompt = f"""
Review the code changes made for this issue:

# {issue.title}

{issue.body}

Please review the implementation for:
1. Correctness - Does it solve the issue?
2. Code quality - Is it clean, readable, and maintainable?
3. Security - Are there any security concerns?
4. Performance - Are there any performance issues?

If you find issues, list them clearly.
If the implementation is good, say "APPROVED" and explain why it's acceptable.
"""
        review_result = yield RunAgent(env=env, prompt=review_prompt, name="reviewer")
        last_review = review_result

        if "approved" in review_result.lower():
            review_approved = True
            break

        if iteration < max_reviews:
            # Have implementer address review feedback
            fix_prompt = f"""
A code review found the following issues:

{review_result}

Please address these review comments and improve the implementation.
"""
            yield RunAgent(env=env, prompt=fix_prompt, name="implementer")

    # Step 4: Commit and push
    commit_msg = f"feat: {issue.title}\n\nResolves: {issue.id}"
    yield Commit(env=env, message=commit_msg)
    yield Push(env=env)

    # Step 5: Create PR
    review_status = "approved" if review_approved else f"after {max_reviews + 1} reviews"

    pr = yield CreatePR(
        env=env,
        title=issue.title,
        body=f"""
## Summary

Implements {issue.id}: {issue.title}

## Changes

{issue.body}

## Review Status

Code review: {review_status}

### Last Review

{last_review}

---
Generated by doeff-conductor reviewed_pr template
""",
    )

    # Step 6: Resolve the issue
    yield ResolveIssue(issue=issue, pr_url=pr.url)

    return pr


__all__ = ["reviewed_pr"]
