"""impls/fast_jev.hy の公開面の型(Python の読み手 = 検)。defk は Program を返す — Python から値を読むには `run(...)`。"""

from typing import Any

from doeff import Program

FAST_JEV_PLUGIN_ID: str
FAST_JEV_MARKETPLACE_NAME: str
FAST_JEV_MARKETPLACE_URL: str
FAST_JEV_KEY_FILE_ENV: str
FAST_JEV_CACHE_TTL_MINUTES: int
FAST_JEV_PLUGIN_VERSION: str
FAST_JEV_PLUGIN_JSON_SUFFIX: str
FAST_JEV_STATE_DIR_SUFFIX: str
FAST_JEV_PLUGIN_DEFAULT_TTL_MINUTES: int
FAST_JEV_WARM_MARGIN_MS: int

def fast_jev_plugin_options(settings_text: str | None) -> Program[dict[str, Any], Any]: ...
def fast_jev_session_state_path(settings_text: str | None, session_id: str) -> Program[str | None, Any]: ...
def fast_jev_cache_surely_warm(
    settings_text: str | None, state_text: str | None, config_dir: str, model: str | None, now_ms: int
) -> Program[bool, Any]: ...

def fast_jev_state_dir(home: str) -> Program[str, Any]: ...
def fast_jev_compaction_enabled(settings_text: str | None) -> Program[bool, Any]: ...
def fast_jev_home_settings(settings_text: str | None, key_file: str, state_dir: str) -> Program[str, Any]: ...
def fast_jev_install_command(config_dir: str) -> Program[str, Any]: ...
def fast_jev_plugin_json_path(config_dir: str) -> Program[str, Any]: ...
def fast_jev_installed_version(plugin_json_text: str | None) -> Program[str | None, Any]: ...
def fast_jev_plugin_outdated(installed_version: str | None) -> Program[bool, Any]: ...
def fast_jev_update_command(config_dir: str) -> Program[str, Any]: ...
