"""impls/headless_argv.hy の公開面の型(Python の読み手 = 検)。defk は Program を返す — Python から値を読むには `run(...)`。"""

from typing import Any

from doeff import Program

CLAUDE_HEADLESS_FLAGS: list[str]
CODEX_APP_SERVER_ARGS: list[str]
CLAUDE_COLD_COMPACTION_PROMPT: str

def fast_jev_compaction_enabled(settings_text: str | None) -> Program[bool, Any]: ...
def argv_with_settings_env(argv: list[str], env: dict[str, str]) -> Program[list[str], Any]: ...
def cold_compaction_argv(base: list[str], conv_id: str) -> Program[list[str], Any]: ...

def build_claude_headless(params: dict[str, object]) -> Program[dict[str, object], Any]: ...
def build_codex_headless(params: dict[str, object]) -> Program[dict[str, object], Any]: ...
def build_headless(agent_type: str, params: dict[str, object]) -> Program[dict[str, object], Any]: ...
