"""impls/headless_argv.hy の公開面の型(Python の読み手 = 検)。deff は普通の関数。"""

CLAUDE_HEADLESS_FLAGS: list[str]
CODEX_APP_SERVER_ARGS: list[str]

def build_claude_headless(params: dict[str, object]) -> dict[str, object]: ...
def build_codex_headless(params: dict[str, object]) -> dict[str, object]: ...
def build_headless(agent_type: str, params: dict[str, object]) -> dict[str, object]: ...
