from doeff import Program

from .effects import JSONObject

# Programは現行VMでは非genericなunion。結果の型はHyのpost契約が検査する。
def response_time_ms(text: str | None) -> Program: ...
def cache_observation_of(records: tuple) -> Program: ...
def with_request_start_bound(
    observation: JSONObject | None, before_start_ms: int | None, covers_turn: bool
) -> Program: ...
def cache_context_of(
    status: JSONObject | None, account: str | None
) -> Program: ...
