"""join.hy の公開面の型(共通の品質検査が Hy の投影と突合する・Python の読み手 = runtime / test)。

defk は Program を返す(引数の型 = :pre の契約・実行後の値の型 = :post)。
"""

from doeff import Program
from doeff_agents.sessionhost.acp.effects import (
    JoinArgv,
    JoinDeclaration,
    JoinSpec,
    Ownership,
    ProbeAnswer,
)

def config_path_of(argv: JoinArgv) -> Program: ...
def flag_values_of(argv: JoinArgv) -> Program: ...
def declared_values_of(declaration: JoinDeclaration) -> Program: ...
def merged_values_of(flags: dict, declared: dict) -> Program: ...
def ownership_of(grade: str | None, proof: str | None) -> Program: ...
def join_spec_of(argv: JoinArgv, declaration: JoinDeclaration, state_home: str) -> Program: ...
def join_plan_of(spec: JoinSpec) -> Program: ...
def ownership_verdict(ownership: Ownership, answer: ProbeAnswer) -> Program: ...
def ownership_preflight(ownership: Ownership) -> Program: ...
