"""join.hy の公開面の型(共通の品質検査が Hy の投影と突合する・Python の読み手 = runtime / test)。

defk は Program を返す(引数の型 = :pre の契約・実行後の値の型 = :post)。
"""

from doeff import Program
from doeff_agents.sessionhost.acp.effects import (
    JoinArgv,
    JoinDeclaration,
    JoinSpec,
    Ownership,
    ProbeAnswer,
)

#: `join` が受け付ける flag の一覧 = `join --help` の生成元(usage.py が読む唯一の面)。
#: 各項 = (flag, 値の見出し, 説明)。join の flag は全部値を取る。
JOIN_FLAG_SPECS: list[tuple[str, str, str]]
#: 宣言 file を名指す flag(composition root が先に読む)。
FLAG_CONFIG: str
#: 値を取る flag → (宣言 file の表, 鍵)。受け付ける flag はこれと FLAG_CONFIG で全部。
FLAG_KEYS: dict[str, tuple[str, str]]

def config_path_of(argv: JoinArgv) -> Program: ...
def flag_values_of(argv: JoinArgv) -> Program: ...
def declared_values_of(declaration: JoinDeclaration) -> Program: ...
def merged_values_of(flags: dict, declared: dict) -> Program: ...
def ownership_of(grade: str | None, proof: str | None) -> Program: ...
def capacity_of(text: str | None) -> Program: ...
def drain_seconds_of(text: str | None) -> Program: ...
def revision_of(text: str | None) -> Program: ...
def build_of(text: str | None) -> Program: ...
def places_of(text: str | None) -> Program: ...
def seat_env_of(text: str | None) -> Program: ...
def declaration_sha256_of(text: str | None) -> Program: ...
def work_roots_of(text: str | None) -> Program: ...
def work_dir_root_shaped(root: str) -> Program: ...
def work_dir_roots_of(text: str | None) -> Program: ...
def held_work_dir_roots_of(entries: tuple) -> Program: ...
def join_spec_of(argv: JoinArgv, declaration: JoinDeclaration, state_home: str) -> Program: ...
def record_sink_of(url: str | None) -> Program: ...
def join_plan_of(spec: JoinSpec) -> Program: ...
def custody_contract_refusal(answer: dict | None, spoken: int) -> Program: ...
def custody_contract_preflight(spoken: int) -> Program: ...
def ownership_verdict(ownership: Ownership, answer: ProbeAnswer) -> Program: ...
def ownership_preflight(ownership: Ownership) -> Program: ...
