"""judgment.hy の公開面の型(共通の品質検査が Hy の投影と突合する・Python の読み手 = test)。

defk は Program を返す(引数の型 = :pre の契約・実行後の値の型 = :post)。
"""

from doeff import Program
from doeff_agents.sessionhost.acp.effects import (
    AcpRow,
    AgentdSettings,
    ArmChoice,
    AgentdState,
    InFlightJob,
    LaunchPlan,
    LeaseGrant,
    ProfileUsage,
    ProfileUsageUnavailable,
    SessionView,
    WatchAdvance,
)

def bound_to_me(row: AcpRow, node_name: str) -> Program: ...
def job_rows_bound_to(rows: tuple, node_name: str) -> Program: ...
def session_id_of_handle(row: AcpRow) -> Program: ...
def running_on_me(row: AcpRow, node_name: str, principal: str) -> Program: ...
def job_rows_running_on(rows: tuple, node_name: str, principal: str) -> Program: ...
def job_step_of(view: SessionView | None, floor_ms: int, progressed: bool) -> Program: ...
def launch_lifecycle_of(charter: dict) -> Program: ...
def session_alive(view: SessionView | None) -> Program: ...
def session_idle(view: SessionView | None) -> Program: ...
def session_busy(view: SessionView | None) -> Program: ...
def handle_owned_by(row: AcpRow, node_name: str, principal: str) -> Program: ...
def conversation_session_of(
    rows: tuple, subject: str, node_name: str, principal: str
) -> Program: ...
def warm_candidate_of(
    plan: LaunchPlan, rows: tuple, subject: str, node_name: str, principal: str
) -> Program: ...
def home_key_of(plan: LaunchPlan) -> Program: ...
def attribution_of_view(view: SessionView) -> Program: ...
def session_attribution_of(plan: LaunchPlan, job_id: str, subject: str, arm: str) -> Program: ...
def charter_with_attribution(charter: dict, attribution: dict) -> Program: ...
def session_in_home(view: SessionView, home: dict) -> Program: ...
def next_arm_for_job(candidate: str | None, view: SessionView | None, home: dict) -> Program: ...
def fallback_arm_of(choice: ArmChoice) -> Program: ...
def recovered_arm_of(plan: LaunchPlan, view: SessionView, job_id: str) -> Program: ...
def cleanup_after_end(view: SessionView) -> Program: ...
def sessions_to_retire(views: tuple, now_ms: int, ttl_seconds: int) -> Program: ...
def withdrawn_session_ids_of(rows: tuple, node_name: str, principal: str) -> Program: ...
def withdrawn_rows_of(rows: tuple, node_name: str, principal: str) -> Program: ...
def list_mode_for(
    signal: WatchAdvance, state: AgentdState, now_ms: int, settings: AgentdSettings
) -> Program: ...
def rows_of_kind(rows: tuple, kind: str) -> Program: ...
def merge_rows(known: tuple, changed: tuple, retired: tuple) -> Program: ...
def births_of_rows(rows: tuple) -> Program: ...
def births_with(births: tuple, pairs: tuple) -> Program: ...
def birth_ms_of(row: AcpRow, births: tuple) -> Program: ...
def message_key_of(message_id: str) -> Program: ...
def interrupt_arm_for(job: InFlightJob, view: SessionView | None) -> Program: ...
def interrupted_status_of(status: dict) -> Program: ...
def stream_capability_of_backend(backend: str) -> Program: ...
def stream_source_of(view: SessionView, canonical_work_dir: str) -> Program: ...
def events_to_deltas(agent_type: str, text: str, job_id: str, seq_start: int, at: int) -> Program: ...
def codex_event_deltas_of(records: tuple, job_id: str, seq_start: int, at: int) -> Program: ...
def session_observations_of(views: tuple) -> Program: ...
def transcript_candidates_of(views: tuple, sessions: list, limit: int) -> Program: ...
def transcript_observation_of(view: SessionView) -> Program: ...
def status_object_of(row: AcpRow) -> Program: ...
def running_status_of(row: AcpRow, session_id: str, principal: str) -> Program: ...
def condition_of(condition_type: str, reason: str) -> Program: ...
def ended_status_of(
    status: dict, result: dict | list | str | int | float | bool | None, conditions: tuple
) -> Program: ...
def launch_plan_of(row: AcpRow) -> Program: ...
def charter_with_session_id(charter: dict, session_id: str) -> Program: ...
def first_turn_carries_inputs(backend_kind: str, arm: str) -> Program: ...
def first_turn_prompt_of(charter_prompt: str, bodies: tuple) -> Program: ...
def charter_with_first_turn(charter: dict, bodies: tuple) -> Program: ...
def charter_with_history(charter: dict, history: str) -> Program: ...
def incarnation_charter_of(
    plan: LaunchPlan,
    choice: ArmChoice,
    session_id: str,
    bodies: tuple,
    history: str,
    attribution: dict,
    backend_kind: str,
    lease: LeaseGrant | None,
    homes_root: str,
) -> Program: ...
def history_time_of(at: int) -> Program: ...
def history_message_line(message: AcpRow, at: int) -> Program: ...
def history_entry_line(entry: dict, at: int) -> Program: ...
def rehydrate_history_of(
    conversation_id: str, messages: tuple, records: tuple, exclude: tuple, budget: int
) -> Program: ...
def inputs_of(row: AcpRow) -> Program: ...
def resume_params_of(predecessor: str, charter: dict) -> Program: ...
def charter_with_grant(
    charter: dict,
    lease_kind: str,
    account: str,
    grant_token: str | None,
    auth_json: str | None,
    homes_root: str,
) -> Program: ...
def message_bodies_of(rows: tuple, inputs: tuple) -> Program: ...
def node_row_named(rows: tuple, name: str) -> Program: ...
def node_status_with_lease(
    row: AcpRow, settings: AgentdSettings, now_ms: int, sessions: list, transcripts: list
) -> Program: ...
def profile_rows_active(rows: tuple) -> Program: ...
def profile_rows_held(active: tuple, homes: tuple) -> Program: ...
def usage_by_profile(outcomes: tuple) -> Program: ...
def observed_window_of(row: AcpRow) -> Program: ...
def profile_observed_of(
    row: AcpRow, usage: ProfileUsage | ProfileUsageUnavailable | None, node_name: str
) -> Program: ...
def profile_observed_changed(row: AcpRow, observed: dict) -> Program: ...
def profile_status_with_observed(row: AcpRow, observed: dict) -> Program: ...
def turn_record_key_of(job_id: str) -> Program: ...
def in_flight_job_of(
    row: AcpRow,
    plan: LaunchPlan,
    view: SessionView,
    node_name: str,
    started_ms: int,
    turn_floor_ms: int,
    start_offset: int,
    lease: LeaseGrant | None,
    pending: tuple,
) -> Program: ...
def turn_record_spec_of(job: InFlightJob) -> Program: ...
def entries_of_status(status: dict) -> Program: ...
def next_seq_after(entries: tuple, floor: int) -> Program: ...
def renumbered_entries(entries: tuple, floor: int) -> Program: ...
def entry_bytes(entry: dict) -> Program: ...
def drop_marker(dropped: int, seq: int, at: int) -> Program: ...
def is_drop_marker(entry: dict) -> Program: ...
def marker_bytes(dropped: int, seq: int, at: int) -> Program: ...
def entries_within_budget(entries: tuple, budget: int) -> Program: ...
def turn_record_appended_status(status: dict, new_entries: tuple) -> Program: ...
def turn_record_ended_status(status: dict, usage: dict | None, entries: tuple) -> Program: ...
def transcript_path_of(view: SessionView, canonical_work_dir: str) -> Program: ...
def usage_of_claude_message(usage: dict, model: str | None) -> Program: ...
def add_usage(total: dict | None, part: dict) -> Program: ...
def parse_json_lines(text: str) -> Program: ...
def summary_of(value: dict | list | str | int | float | bool | None, limit: int) -> Program: ...
def clipped(text: str, limit: int) -> Program: ...
def text_entry(seq: int, at: int, text: str, model: str | None) -> Program: ...
def tool_use_entry(
    seq: int, at: int, tool_id: str, name: str, input: dict | list | str | int | float | bool | None
) -> Program: ...
def tool_result_entry(
    seq: int,
    at: int,
    tool_id: str,
    output: dict | list | str | int | float | bool | None,
    is_error: bool,
) -> Program: ...
def note_entry(seq: int, at: int, kind: str, text: str) -> Program: ...
def claude_system_note(record: dict) -> Program: ...
def claude_result_error(record: dict) -> Program: ...
def delta_frame(job_id: str, seq: int, at: int, kind: str, payload: dict) -> Program: ...
def claude_deltas_of(
    records: tuple, job_id: str, seq_start: int, at: int, streamed: bool
) -> Program: ...
def codex_deltas_of(records: tuple, job_id: str, seq_start: int, at: int) -> Program: ...
def deltas_of(
    agent_type: str, source: str, text: str, job_id: str, seq_start: int, at: int
) -> Program: ...
def pane_frame(job_id: str, seq: int, at: int, lines: tuple) -> Program: ...
def status_frame(job_id: str, seq: int, at: int, phase: str) -> Program: ...
def frame_lines_of(text: str) -> Program: ...
def capture_verdict(subscribers: int | None) -> Program: ...
def wait_seconds_for(state: AgentdState, settings: AgentdSettings) -> Program: ...
def due(last_ms: int | None, now_ms: int, period_seconds: int | float) -> Program: ...
def resync_due(
    signal: WatchAdvance, state: AgentdState, now_ms: int, settings: AgentdSettings
) -> Program: ...
def lease_renew_due(job: InFlightJob, now_ms: int, settings: AgentdSettings) -> Program: ...
def job_outcome_of(view: SessionView) -> Program: ...
def without_job(state: AgentdState, job_id: str) -> Program: ...
def with_job(state: AgentdState, job: InFlightJob) -> Program: ...
def in_flight_ids(state: AgentdState) -> Program: ...
