"""judgment.hy の公開面の型(共通の品質検査が Hy の投影と突合する・Python の読み手 = test)。

defk は Program を返す(引数の型 = :pre の契約・実行後の値の型 = :post)。
"""

from doeff import Program
from doeff_agents.sessionhost.acp.effects import (
    AcpRow,
    AgentdSettings,
    ArmChoice,
    AgentdState,
    Conflict,
    DeltaBatch,
    HeadlineCounts,
    HeadlineTurns,
    CommandExited,
    CommandGone,
    CommandRunning,
    InFlightCommand,
    HistorySummary,
    InFlightSummarize,
    SummarizePlan,
    SummaryOutcome,
    SummaryRegion,
    InFlightJob,
    JobCancel,
    JobOutcome,
    UnrecordedEnd,
    LaunchPlan,
    VerifyPlan,
    LeaseGrant,
    ProfileUsage,
    ProfileUsageUnavailable,
    RecordAppended,
    RecordConflicted,
    RecordEvent,
    RecordPage,
    RecordUnread,
    RecordUnsent,
    RecordedTurns,
    Refused,
    SessionView,
    TurnEntryDropMarker,
    TurnEntryHeadline,
    WatchAdvance,
    Written,
)

# 段 12 lane 12j(agora-redesign #321): 結びが自分を指すか = nodeRow(行の id)が在ればそれ・無ければ名前(1 点)
def binding_names_me(binding: dict | None, node_name: str, node_row_id: str | None) -> Program: ...
def bound_to_me(row: AcpRow, node_name: str, node_row_id: str | None) -> Program: ...
def job_rows_bound_to(rows: tuple, node_name: str, node_row_id: str | None) -> Program: ...
def session_id_of_handle(row: AcpRow) -> Program: ...
def running_on_me(row: AcpRow, node_name: str, node_row_id: str | None, principal: str) -> Program: ...
def job_rows_running_on(rows: tuple, node_name: str, node_row_id: str | None, principal: str) -> Program: ...
def job_step_of(view: SessionView | None, floor_ms: int, progressed: bool) -> Program: ...
def launch_lifecycle_of(charter: dict) -> Program: ...
def session_alive(view: SessionView | None) -> Program: ...
def backend_alive(view: SessionView | None) -> Program: ...
def retire_reason_of(choice: ArmChoice, view: SessionView | None, job_id: str) -> Program: ...
def provider_limit_condition_of(cause: dict | None, model: str | None) -> Program: ...
def session_lost_condition_of(view: SessionView, now_ms: int) -> Program: ...
def restart_condition_of(job: InFlightJob, node_name: str, reason: str, now_ms: int) -> Program: ...
def session_idle(view: SessionView | None) -> Program: ...
def session_busy(view: SessionView | None) -> Program: ...
def handle_owned_by(row: AcpRow, node_name: str, node_row_id: str | None, principal: str) -> Program: ...
def conversation_session_of(
    rows: tuple, subject: str, node_name: str, node_row_id: str | None, principal: str
) -> Program: ...
def warm_candidate_of(
    plan: LaunchPlan, rows: tuple, subject: str, node_name: str, node_row_id: str | None, principal: str
) -> Program: ...
def session_affinity_key_of(plan: LaunchPlan) -> Program: ...
def attribution_of_view(view: SessionView) -> Program: ...
def session_attribution_of(plan: LaunchPlan, job_id: str, subject: str, arm: str) -> Program: ...
def charter_with_attribution(charter: dict, attribution: dict) -> Program: ...
def session_in_home(view: SessionView, home: dict) -> Program: ...
def conversation_recorded_of(probe: RecordPage | RecordUnread | None) -> Program: ...
def next_arm_for_job(candidate: str | None, view: SessionView | None, home: dict, effort: str | None, compact: bool) -> Program: ...
def fresh_start_asks_record(choice: ArmChoice, settings: AgentdSettings) -> Program: ...
def fresh_start_arm_of(choice: ArmChoice, recorded: bool) -> Program: ...
def conversation_key_of(conversation_id: str) -> Program: ...
def compact_at_of(row: AcpRow | None) -> Program: ...
def context_percent_of(context: dict | None) -> Program: ...
def compaction_due(compact_at: int | None, percent: int | None) -> Program: ...
def context_percent_for(state: AgentdState, session_id: str | None) -> Program: ...
def with_context_percent(state: AgentdState, session_id: str, percent: int | None) -> Program: ...
def codex_context_of(last: dict | None, window: int | None) -> Program: ...
def conversation_opener_of(row: AcpRow | None) -> Program: ...
def charter_with_conversation_env(charter: dict, conversation_id: str, opener: str | None) -> Program: ...
def session_effort_of(view: SessionView) -> Program: ...
def plan_with_node_home(plan: LaunchPlan, home: str) -> Program: ...
def work_dir_of(plan: LaunchPlan) -> Program: ...
def work_dir_step_of(plan: LaunchPlan, exists: bool) -> Program: ...
def effort_of_plan(plan: LaunchPlan) -> Program: ...
def ignored_settings_of(plan: LaunchPlan, view: SessionView | None, arm: str) -> Program: ...
def capabilities_of() -> Program: ...
def fallback_arm_of(choice: ArmChoice) -> Program: ...
def recovered_arm_of(plan: LaunchPlan, view: SessionView, job_id: str) -> Program: ...
def cleanup_after_end(view: SessionView) -> Program: ...
def sessions_to_retire(views: tuple, now_ms: int, ttl_seconds: int) -> Program: ...
# 段 12 lane 12j(agora-redesign #379): 会話の他の家に残る温かい session(1 会話 1 温かい session)
def stale_conversation_sessions_of(views: tuple, subject: str, home: dict, keep_session_id: str) -> Program: ...
def withdrawn_session_ids_of(rows: tuple, node_name: str, node_row_id: str | None, principal: str) -> Program: ...
def withdrawn_rows_of(rows: tuple, node_name: str, node_row_id: str | None, principal: str) -> Program: ...
def list_mode_for(
    signal: WatchAdvance, state: AgentdState, now_ms: int, settings: AgentdSettings
) -> Program: ...
def window_epoch_verdict(known: str | None, announced: str | None) -> Program: ...
def rows_of_kind(rows: tuple, kind: str) -> Program: ...
def merge_rows(known: tuple, changed: tuple, retired: tuple) -> Program: ...
def births_of_rows(rows: tuple) -> Program: ...
def births_with(births: tuple, pairs: tuple) -> Program: ...
def birth_ms_of(row: AcpRow, births: tuple) -> Program: ...
def message_key_of(message_id: str) -> Program: ...
def interrupt_arm_for(job: InFlightJob, view: SessionView | None) -> Program: ...
def interrupted_status_of(status: dict) -> Program: ...
# 段 12 lane 12j(agora-redesign #367): 取り消しの 3 段(合図 → 猶予 → 強制)
def job_cancel_of(row: AcpRow) -> Program: ...
def cancel_deadline_ms(cancel: JobCancel) -> Program: ...
def cancel_arm_for(job: InFlightJob, view: SessionView | None, cancel: JobCancel, now_ms: int) -> Program: ...
def cancel_acknowledged_status_of(status: dict, now_ms: int) -> Program: ...
def cancelled_cause_of(cancel: JobCancel, stage: str) -> Program: ...
# 段 12 lane 12k(agora-redesign #349 行 3 粒 3a): 終端は必ず result.cause を運ぶ
def terminal_cause_of(category: str, reason: str | None) -> Program: ...
def command_cause_of(conditions: tuple) -> Program: ...
def outcome_with_limit(outcome: JobOutcome, limit: dict | None) -> Program: ...
# 依頼 lt-R79KYTYMJH4ZT9X4KHWKCD23KB(D1): 出力 0 件の温かい手番は completed を名乗らない
def turn_produced_nothing_condition_of(
    step: str, source: str | None, path: str | None, batch: DeltaBatch, turn_error: str | None
) -> Program: ...
def outcome_with_nothing(outcome: JobOutcome, nothing: dict | None) -> Program: ...
def result_with_cause(result: dict | list | str | int | float | bool | None, cause: dict) -> Program: ...
def outcome_with_cancel(outcome: JobOutcome, cancel: JobCancel | None, stage: str) -> Program: ...
def recovered_cancel_of(job: InFlightJob, row: AcpRow) -> Program: ...
# 段 12 lane 12j(agora-redesign #402): 着かなかった Ended と置き直された試み
def unrecorded_end_of(job: InFlightJob, result: dict | list | str | int | float | bool | None, cause: dict, conditions: tuple, now_ms: int) -> Program: ...
def end_retry_verdict(row: AcpRow | None, session_id: str, principal: str, at_ms: int, now_ms: int, ttl_ms: int) -> Program: ...
def with_unrecorded_end(state: AgentdState, end: UnrecordedEnd) -> Program: ...
def without_unrecorded_end(state: AgentdState, job_id: str) -> Program: ...
def unrecorded_end_ids(state: AgentdState) -> Program: ...
def rebound_rows_of(rows: tuple, jobs: tuple) -> Program: ...
def string_list_of(status: dict, key: str) -> Program: ...
def pending_interrupts_of(row: AcpRow, sent: tuple) -> Program: ...
def interrupts_delivered_status_of(status: dict, ids: tuple) -> Program: ...
# 段 10 lane 10n(agora-redesign #93): 割り込みの約束(期限・読んだ証拠・止めた印)。
def escalation_seconds_of_charter(charter: dict) -> Program: ...
def with_injected_interrupts(job: InFlightJob, ids: tuple, now_ms: int) -> Program: ...
def unread_interrupts_of(job: InFlightJob) -> Program: ...
def interrupt_reads_of(job: InFlightJob, reads: tuple) -> Program: ...
def interrupts_due_for_escalation(job: InFlightJob, now_ms: int) -> Program: ...
def interrupt_marks_status_of(status: dict, read: tuple, escalated: tuple) -> Program: ...
def status_with_condition(status: dict, condition_type: str, reason: str) -> Program: ...
def interrupt_escalation_undeclared_reason(job: InFlightJob) -> Program: ...
def recovered_interrupts_of(job: InFlightJob, row: AcpRow, now_ms: int) -> Program: ...
def job_row_keyed(rows: tuple, job_key: str) -> Program: ...
def stream_capability_of_backend(backend: str) -> Program: ...
def stream_source_of(view: SessionView, canonical_work_dir: str) -> Program: ...
def events_to_deltas(
    agent_type: str, text: str, job_id: str, seq_start: int, at: int, open_blocks: tuple
) -> Program: ...
def codex_event_deltas_of(records: tuple, job_id: str, seq_start: int, at: int) -> Program: ...
def session_observations_of(views: tuple) -> Program: ...
def profile_accounts_of(rows: tuple) -> Program: ...
def pane_observations_of(seats: tuple, accounts: dict, sessions: list) -> Program: ...
def transcript_candidates_of(views: tuple, sessions: list, limit: int) -> Program: ...
def transcript_observation_of(view: SessionView) -> Program: ...
def status_object_of(row: AcpRow) -> Program: ...
def running_status_of(row: AcpRow, session_id: str, principal: str) -> Program: ...
def condition_of(condition_type: str, reason: str) -> Program: ...
def ended_status_of(
    status: dict, result: dict | list | str | int | float | bool | None, cause: dict, conditions: tuple
) -> Program: ...
def launch_plan_of(row: AcpRow) -> Program: ...
def credential_source_of(plan: LaunchPlan, custody_declared: bool) -> Program: ...
def charter_with_session_id(charter: dict, session_id: str) -> Program: ...
def first_turn_carries_inputs(backend_kind: str, arm: str) -> Program: ...
def send_folds_bodies(backend_kind: str) -> Program: ...
def first_turn_prompt_of(charter_prompt: str, bodies: tuple) -> Program: ...
def charter_with_first_turn(charter: dict, bodies: tuple) -> Program: ...
def charter_with_history(charter: dict, history: str) -> Program: ...
def incarnation_charter_of(
    plan: LaunchPlan,
    choice: ArmChoice,
    session_id: str,
    bodies: tuple,
    history: str,
    attribution: dict,
    backend_kind: str,
    lease: LeaseGrant | None,
    homes_root: str,
    opener: str | None,
) -> Program: ...
def history_time_of(at: int) -> Program: ...
def history_message_line(message: AcpRow, at: int, fetched: dict) -> Program: ...
def history_event_body(event: RecordEvent) -> Program: ...
def history_event_line_of(event: RecordEvent, body: str) -> Program: ...
def history_event_line(event: RecordEvent) -> Program: ...
def history_thin_body(body: str, head_bytes: int) -> Program: ...
def history_event_thin_line(event: RecordEvent, head_bytes: int) -> Program: ...
def headline_counts_of_entries(entries: tuple, at: int) -> Program: ...
def headline_counts_of_items(items: tuple) -> Program: ...
def history_counts_note(counts: HeadlineCounts) -> Program: ...
def history_headline_line(record: AcpRow, counts: HeadlineCounts) -> Program: ...
def history_dropped_headline(
    counts: HeadlineCounts,
    turns: int,
    items: int,
    budget: int,
    where: str,
) -> Program: ...
def history_cut_notice(budget: int, cut_bytes: int, where: str) -> Program: ...
def history_header_of(conversation_id: str, source: RecordedTurns | HeadlineTurns, kept_summaries: int) -> Program: ...
def dropped_headline_counts(items: tuple, summaries: tuple) -> Program: ...
def summary_floor_at_of(page: RecordPage | RecordUnread, floor: int) -> Program: ...
def rehydrate_history_of(
    conversation_id: str,
    messages: tuple,
    source: RecordedTurns | HeadlineTurns,
    exclude: tuple,
    budget: int,
    fetched: dict,
    summaries: tuple,
    floor_at: int | None,
) -> Program: ...
def record_history_satisfied(events: tuple, budget: int) -> Program: ...
def record_page_advances(before: int | None, next: int | None) -> Program: ...
def inputs_of(row: AcpRow) -> Program: ...
def resume_params_of(predecessor: str, charter: dict) -> Program: ...
def charter_with_grant(
    charter: dict,
    lease_kind: str,
    account: str,
    grant_token: str | None,
    auth_json: str | None,
    homes_root: str,
) -> Program: ...
def turn_session_env_of(lease: LeaseGrant | None) -> Program: ...
def message_body_ref_of(spec: dict) -> Program: ...
def mail_text_of(events: tuple) -> Program: ...
def message_attachments_of(spec: dict) -> Program: ...
def attachment_of(events: tuple, headline: tuple) -> Program: ...
def first_turn_attachments_of(carried: tuple) -> Program: ...
def launch_charter_with_attachments(charter: dict, attachments: tuple) -> Program: ...
def mail_heading_of(message_id: str, spec: dict) -> Program: ...
def mail_turn_text_of(message_id: str, spec: dict, body: str) -> Program: ...
def message_bodies_of(rows: tuple, inputs: tuple, fetched: dict, carried: dict) -> Program: ...
def node_resource_id_of(rows: tuple, name: str) -> Program: ...
def node_row_named(rows: tuple, name: str) -> Program: ...
# 段 12(agora-redesign #537 便 1): 生きている node の名の集合(巡回が『この記録の機体はまだ居るか』を引く)
def live_node_names_of(rows: tuple) -> Program: ...
# 段 12 lane 12j(agora-redesign #320): 行 → library の項(綴りの読みの 1 点)
def node_row_entry_of(row: AcpRow) -> Program: ...
def agentd_version_of(settings: AgentdSettings) -> Program: ...
def node_labels_of(settings: AgentdSettings, labels: dict) -> Program: ...
def node_places_of(settings: AgentdSettings, spec: dict) -> Program: ...
def node_work_roots_of(settings: AgentdSettings, spec: dict) -> Program: ...
def node_work_dir_roots_of(settings: AgentdSettings, spec: dict) -> Program: ...
def declared_capacity_of(settings: AgentdSettings) -> Program: ...
def node_spec_of(settings: AgentdSettings) -> Program: ...
def node_spec_declared(spec: dict, settings: AgentdSettings) -> Program: ...
def node_lease_of(settings: AgentdSettings, now_ms: int) -> Program: ...
def node_status_with_renewed_lease(row: AcpRow, settings: AgentdSettings, now_ms: int) -> Program: ...
def node_status_with_observations(
    row: AcpRow, settings: AgentdSettings, sessions: list, transcripts: list
) -> Program: ...
def profile_key_of(profile: str) -> Program: ...
def credential_from_custody(source: str) -> Program: ...
def credential_place_of(row: AcpRow | None) -> Program: ...
def credential_place_mismatch(places: tuple, boundary: str | None) -> Program: ...
def charter_place_of(row: AcpRow) -> Program: ...
def place_mismatch(places: tuple, place: str | None) -> Program: ...
def profile_rows_active(rows: tuple) -> Program: ...
def profile_rows_held(active: tuple, homes: tuple, settings: AgentdSettings) -> Program: ...
def usage_by_profile(outcomes: tuple) -> Program: ...
def observed_window_of(row: AcpRow) -> Program: ...
def profile_observed_of(
    row: AcpRow, usage: ProfileUsage | ProfileUsageUnavailable | None, node_name: str
) -> Program: ...
def profile_observed_changed(row: AcpRow, observed: dict, node_name: str) -> Program: ...
def profile_latest_should_replace(current: dict | None, observed: dict, period_ms: int) -> Program: ...
def profile_status_with_observed(row: AcpRow, observed: dict, node_name: str, period_ms: int) -> Program: ...
def turn_record_key_of(job_id: str) -> Program: ...
def in_flight_job_of(
    row: AcpRow,
    plan: LaunchPlan,
    view: SessionView,
    node_name: str,
    started_ms: int,
    turn_floor_ms: int,
    start_offset: int,
    lease: LeaseGrant | None,
    pending: tuple,
) -> Program: ...
def turn_record_spec_of(job: InFlightJob) -> Program: ...
def entries_of_status(status: dict) -> Program: ...
def next_seq_after(entries: tuple, floor: int) -> Program: ...
def renumbered_entries(entries: tuple, floor: int) -> Program: ...
def entry_bytes(entry: dict) -> Program: ...
def drop_marker(dropped: int, seq: int, at: int) -> Program: ...
def is_drop_marker(entry: dict) -> Program: ...
def marker_bytes(dropped: int, seq: int, at: int) -> Program: ...
def entries_within_budget(entries: tuple, budget: int) -> Program: ...
def turn_record_appended_status(status: dict, new_entries: tuple) -> Program: ...
def turn_record_ended_status(status: dict, usage: dict | None, entries: tuple) -> Program: ...
# 段 12(agora-redesign #537 便 1): 走っている turn-record を終状態から閉じるか(閉語彙 TurnRecordSweepVerdict)
def turn_record_sweep_verdict(
    record: AcpRow,
    pair: AcpRow | None,
    node_name: str,
    live_nodes: frozenset,
    in_flight_ids: set,
) -> Program: ...
def record_stream_id_of(job_id: str, attempt: int) -> Program: ...
def record_stream_of(job: InFlightJob) -> Program: ...
def record_ref_of(conversation_id: str, stream_id: str) -> Program: ...
def record_stream_job_of(stream_id: str) -> Program: ...
def turn_record_recorded_status(status: dict, record_ref: str, highest: int) -> Program: ...
def record_spool_key_of(stream_id: str, first_seq: int, last_seq: int) -> Program: ...
def record_batches_of(job: InFlightJob, bodies: tuple) -> Program: ...
def record_append_word_of(outcome: RecordAppended | RecordConflicted | RecordUnsent) -> Program: ...
def record_unavailable_noted(job: InFlightJob, reason: str) -> Program: ...
def record_given_up_noted(state: AgentdState, stream_id: str, reason: str) -> Program: ...
def record_flush_due(state: AgentdState, now_ms: int, settings: AgentdSettings) -> Program: ...
def record_refusal_deterministic(status: int) -> Program: ...
def record_create_verdict(
    outcome: Written | Conflict | Refused,
    started_ms: int,
    now_ms: int,
    deadline_seconds: int | float,
    final: bool,
) -> Program: ...
def record_create_applied(
    job: InFlightJob,
    outcome: Written | Conflict | Refused,
    now_ms: int,
    deadline_seconds: int | float,
    final: bool,
) -> Program: ...
def record_create_due(job: InFlightJob, now_ms: int, settings: AgentdSettings) -> Program: ...
def record_lag_of(jobs: tuple, stream_id: str, highest: int) -> Program: ...
def recovered_record_of(record: AcpRow | None) -> Program: ...
def transcript_path_of(view: SessionView, canonical_work_dir: str) -> Program: ...
def usage_of_claude_message(usage: dict, model: str | None) -> Program: ...
def add_usage(total: dict | None, part: dict) -> Program: ...
def parse_json_lines(text: str) -> Program: ...
def summary_of(value: dict | list | str | int | float | bool | None, limit: int) -> Program: ...
def record_body_of(body: dict) -> Program: ...
def record_body_bytes_of(body: dict) -> Program: ...
def text_body(seq: int, at: int, text: str, model: str | None) -> Program: ...
def tool_use_body(
    seq: int, at: int, tool_id: str, name: str, input: dict | list | str | int | float | bool | None
) -> Program: ...
def tool_result_body(
    seq: int,
    at: int,
    tool_id: str,
    output: dict | list | str | int | float | bool | None,
    is_error: bool,
) -> Program: ...
def note_body(seq: int, at: int, kind: str, text: str) -> Program: ...
def headline_of_body(body: dict) -> Program: ...
def entry_json_of(entry: TurnEntryHeadline | TurnEntryDropMarker) -> Program: ...
def entries_of_bodies(bodies: tuple) -> Program: ...
def claude_system_note(record: dict) -> Program: ...
def claude_result_error(record: dict) -> Program: ...
def delta_frame(job_id: str, seq: int, at: int, kind: str, payload: dict) -> Program: ...
def clip_input(value: dict | list | str | int | float | bool | None, root: str, limit: int) -> Program: ...
def tool_use_frame(
    job_id: str,
    seq: int,
    at: int,
    tool_id: str,
    name: str,
    summary: str,
    given: dict | list | str | int | float | bool | None,
) -> Program: ...
def tool_input_chunks(text: str, limit: int) -> Program: ...
def claude_deltas_of(
    records: tuple, job_id: str, seq_start: int, at: int, streamed: bool, open_blocks: tuple
) -> Program: ...
def codex_deltas_of(records: tuple, job_id: str, seq_start: int, at: int) -> Program: ...
def deltas_of(
    agent_type: str, source: str, text: str, job_id: str, seq_start: int, at: int, open_blocks: tuple
) -> Program: ...
def pane_frame(job_id: str, seq: int, at: int, lines: tuple) -> Program: ...
def status_frame(job_id: str, seq: int, at: int, phase: str) -> Program: ...
def frame_lines_of(text: str) -> Program: ...
def capture_verdict(subscribers: int | None) -> Program: ...
def wait_seconds_for(state: AgentdState, settings: AgentdSettings) -> Program: ...
def due(last_ms: int | None, now_ms: int, period_seconds: int | float) -> Program: ...
def record_due(job: InFlightJob, now_ms: int, settings: AgentdSettings) -> Program: ...
def resync_due(
    signal: WatchAdvance, state: AgentdState, now_ms: int, settings: AgentdSettings
) -> Program: ...
def lease_renew_due(job: InFlightJob, now_ms: int, settings: AgentdSettings) -> Program: ...
def job_outcome_of(view: SessionView) -> Program: ...
def without_job(state: AgentdState, job_id: str) -> Program: ...
def with_job(state: AgentdState, job: InFlightJob) -> Program: ...
def in_flight_ids(state: AgentdState) -> Program: ...

# 段 12 lane 12a(agora-redesign #230): verify の命令の判断
def job_kind_of(row: AcpRow) -> Program: ...
def verify_plan_of(row: AcpRow, home: str, runs_dir: str) -> Program: ...
def verify_argv_of(plan: VerifyPlan) -> Program: ...
def verify_handle_of(plan: VerifyPlan, principal: str, started_ms: int) -> Program: ...
def verify_running_status_of(row: AcpRow, handle: dict) -> Program: ...
def verify_plan_of_handle(row: AcpRow) -> Program: ...
def verify_started_ms_of_handle(row: AcpRow, fallback_ms: int) -> Program: ...
def in_flight_command_of(
    row: AcpRow, plan: VerifyPlan, pid: int | None, started_ms: int
) -> Program: ...
def pid_of_text(text: str | None) -> Program: ...
def rc_of_text(text: str | None) -> Program: ...
def verify_step_of(
    probe: CommandRunning | CommandExited | CommandGone, started_ms: int, now_ms: int, deadline_seconds: int
) -> Program: ...
def verify_result_of(command: InFlightCommand, rc: int, ended_ms: int) -> Program: ...
def withdrawn_command_rows_of(rows: tuple, node_name: str, node_row_id: str | None, principal: str) -> Program: ...
def without_command(state: AgentdState, job_id: str) -> Program: ...
def with_command(state: AgentdState, command: InFlightCommand) -> Program: ...

# 段 12 lane 12j(agora-redesign #233): 会話の履歴の段階つき要約(charter.kind = summarize)の判断
def summarize_plan_of(row: AcpRow, default_region_bytes: int, default_deadline_seconds: int) -> Program: ...
def summary_rows_covered_to(rows: tuple, conversation_id: str) -> Program: ...
def summary_region_of(events: tuple, from_seq: int, until: int, budget: int) -> Program: ...
def summary_region_text(region: SummaryRegion) -> Program: ...
def summarize_prompt_of(conversation_id: str, region: SummaryRegion, text: str) -> Program: ...
def summarize_paths_of(runs_dir: str, job_id: str, region: SummaryRegion, started_ms: int) -> Program: ...
def summarize_argv_of(claude_binary: str, model: str, paths: dict) -> Program: ...
def claude_home_of(homes_root: str, account: str) -> Program: ...
def summarize_env_of(token: str, config_dir: str) -> Program: ...
def summarize_handle_of(
    plan: SummarizePlan, region: SummaryRegion, paths: dict, principal: str, started_ms: int, regions_done: int
) -> Program: ...
def summarize_running_status_of(row: AcpRow, handle: dict) -> Program: ...
def in_flight_summarize_of(
    job_key: str,
    job_namespace: str,
    plan: SummarizePlan,
    region: SummaryRegion,
    paths: dict,
    pid: int | None,
    lease_id: str | None,
    started_ms: int,
    regions_done: int,
) -> Program: ...
def summarize_plan_of_command(command: InFlightSummarize) -> Program: ...
def summarize_of_handle(row: AcpRow, default_deadline_seconds: int) -> Program: ...
def summarize_output_of(text: str | None) -> Program: ...
def summary_stream_id_of(from_seq: int, to_seq: int) -> Program: ...
def summary_body_of(text: str, at: int, model: str) -> Program: ...
def summary_batch_of(
    conversation_id: str, stream_id: str, body: dict, started_at_ms: int, node: str, profile: str
) -> Program: ...
def summary_row_id_of(conversation_id: str, to_seq: int) -> Program: ...
def summary_spec_of(command: InFlightSummarize, record_ref: str, body_bytes: int, sha256: str) -> Program: ...
def summary_status_of(model: str, at: int, usage: dict | None) -> Program: ...
def summarize_result_of(command: InFlightSummarize, regions_done: int, ended_ms: int) -> Program: ...
def summarize_empty_result_of(plan: SummarizePlan, from_seq: int, ended_ms: int) -> Program: ...
def withdrawn_summarize_rows_of(rows: tuple, node_name: str, node_row_id: str | None, principal: str) -> Program: ...
def without_summarize(state: AgentdState, job_id: str) -> Program: ...
def with_summarize(state: AgentdState, command: InFlightSummarize) -> Program: ...
def in_flight_summarize_ids(state: AgentdState) -> Program: ...
def in_flight_command_ids(state: AgentdState) -> Program: ...

# 段 12 lane 12j 便 3(agora-redesign #233): 要約の契機と、再開が読む要約の判断
def summarize_due(context: dict | None, trigger_tokens: int) -> Program: ...
def turn_floor_of(events: tuple) -> Program: ...
def summarize_job_id_of(conversation_id: str, until: int) -> Program: ...
def summarize_job_spec_of(conversation_id: str, until: int, model: str) -> Program: ...
def summary_stream_id_of_ref(record_ref: str | None) -> Program: ...
def history_summary_of(row: AcpRow, text: str) -> Program: ...
def summary_floor_of(summaries: tuple) -> Program: ...
def history_summary_line(summary: HistorySummary) -> Program: ...

