"""judgment.hy の公開面の型(共通の品質検査が Hy の投影と突合する・Python の読み手 = test)。

defk は Program を返す(引数の型 = :pre の契約・実行後の値の型 = :post)。
"""

from doeff import Program
from doeff_agents.sessionhost.acp.effects import (
    AcpRow,
    AgentdSettings,
    AgentdState,
    InFlightJob,
    LaunchPlan,
    LeaseGrant,
    SessionView,
    WatchAdvance,
)

def bound_to_me(row: AcpRow, node_name: str) -> Program: ...
def job_rows_bound_to(rows: tuple, node_name: str) -> Program: ...
def session_id_of_handle(row: AcpRow) -> Program: ...
def running_on_me(row: AcpRow, node_name: str, principal: str) -> Program: ...
def job_rows_running_on(rows: tuple, node_name: str, principal: str) -> Program: ...
def job_step_of(view: SessionView | None) -> Program: ...
def status_object_of(row: AcpRow) -> Program: ...
def running_status_of(row: AcpRow, session_id: str, principal: str) -> Program: ...
def condition_of(condition_type: str, reason: str) -> Program: ...
def ended_status_of(
    status: dict, result: dict | list | str | int | float | bool | None, conditions: tuple
) -> Program: ...
def launch_plan_of(row: AcpRow) -> Program: ...
def inputs_of(row: AcpRow) -> Program: ...
def resume_params_of(predecessor: str, charter: dict) -> Program: ...
def charter_with_grant(
    charter: dict,
    lease_kind: str,
    account: str,
    grant_token: str | None,
    auth_json: str | None,
    homes_root: str,
) -> Program: ...
def message_bodies_of(rows: tuple, inputs: tuple) -> Program: ...
def node_row_named(rows: tuple, name: str) -> Program: ...
def node_status_with_lease(
    row: AcpRow, settings: AgentdSettings, now_ms: int, sessions: int
) -> Program: ...
def turn_record_key_of(job_id: str) -> Program: ...
def in_flight_job_of(
    row: AcpRow,
    plan: LaunchPlan,
    view: SessionView,
    node_name: str,
    started_ms: int,
    start_offset: int,
    lease: LeaseGrant | None,
    pending: tuple,
) -> Program: ...
def turn_record_spec_of(job: InFlightJob) -> Program: ...
def turn_record_ended_status(status: dict, usage: dict | None, entries: tuple) -> Program: ...
def transcript_path_of(view: SessionView, canonical_work_dir: str) -> Program: ...
def usage_of_claude_message(usage: dict, model: str | None) -> Program: ...
def add_usage(total: dict | None, part: dict) -> Program: ...
def parse_json_lines(text: str) -> Program: ...
def summary_of(value: dict | list | str | int | float | bool | None, limit: int) -> Program: ...
def delta_frame(job_id: str, seq: int, at: int, kind: str, payload: dict) -> Program: ...
def claude_deltas_of(records: tuple, job_id: str, seq_start: int, at: int) -> Program: ...
def codex_deltas_of(records: tuple, job_id: str, seq_start: int, at: int) -> Program: ...
def deltas_of(agent_type: str, text: str, job_id: str, seq_start: int, at: int) -> Program: ...
def pane_frame(job_id: str, seq: int, at: int, lines: tuple) -> Program: ...
def status_frame(job_id: str, seq: int, at: int, phase: str) -> Program: ...
def frame_lines_of(text: str) -> Program: ...
def capture_verdict(subscribers: int | None) -> Program: ...
def wait_seconds_for(state: AgentdState, settings: AgentdSettings) -> Program: ...
def due(last_ms: int | None, now_ms: int, period_seconds: int | float) -> Program: ...
def resync_due(
    signal: WatchAdvance, state: AgentdState, now_ms: int, settings: AgentdSettings
) -> Program: ...
def lease_renew_due(job: InFlightJob, now_ms: int, settings: AgentdSettings) -> Program: ...
def job_outcome_of(view: SessionView) -> Program: ...
def without_job(state: AgentdState, job_id: str) -> Program: ...
def with_job(state: AgentdState, job: InFlightJob) -> Program: ...
def in_flight_ids(state: AgentdState) -> Program: ...
