from doeff import Program

FROM_OPERATOR: str
FROM_SYSTEM: str
KIND_ASK: str
KIND_ANSWER: str
KIND_ACCEPT: str
KIND_SEND_BACK: str
KIND_WITHDRAW: str
NOTICE_FIELD: str
NONE_WORD: str
SECTION_HEADINGS: dict[str, str]
PREAMBLE_HEADING: str

# Programは現行VMでは非genericなunion。結果の型はHyのpost契約が検査する。
def text_field_of(spec: dict, key: str) -> Program: ...
def refs_field_of(spec: dict) -> Program: ...
def at_field_of(spec: dict) -> Program: ...
def at_text_of(at: int | None) -> Program: ...
def mail_served_class_of(status: dict | None) -> Program: ...
def shown_class_of(spec: dict, status: dict | None) -> Program: ...
def input_source_of(message_id: str, spec: dict, status: dict | None = ...) -> Program: ...
def section_of(source: object) -> Program: ...
def verdict_line_of(source: object) -> Program: ...
def item_heading_of(source: object) -> Program: ...
def turn_input_text_of(message_id: str, spec: dict, body: str, status: dict | None = ...) -> Program: ...
def inputs_text_of(items: tuple) -> Program: ...
def preamble_text_of(charter_prompt: str) -> Program: ...
