from doeff import Program

RESPONSE_TOKEN_FIELDS: tuple[str, ...]
RESPONSE_REQUIRED_TOKENS: tuple[str, ...]
SYNTHETIC_MODEL: str

# Programは現行VMでは非genericなunion。結果の型はHyのpost契約が検査する。
def response_tokens_of(usage: dict) -> Program: ...
def merged_response(known: dict, tokens: dict) -> Program: ...
def compact_bytes(value: dict) -> Program: ...
def response_usages_of(records: tuple) -> Program: ...
def responses_status_of(responses: tuple) -> Program: ...
def usage_of_responses(responses: tuple) -> Program: ...
