"""Public effect API for doeff."""

from __future__ import annotations

from .atomic import (
    AtomicGet,
    AtomicGetEffect,
    AtomicUpdate,
    AtomicUpdateEffect,
    atomic_get,
    atomic_update,
)
from .cache import CacheGet, CacheGetEffect, CachePut, CachePutEffect, cache_get, cache_put
from .durable_cache import (
    DurableCacheDelete,
    DurableCacheExists,
    DurableCacheGet,
    DurableCachePut,
    cachedelete,
    cacheexists,
    cacheget,
    cacheput,
)
from .callstack import (
    ProgramCallFrame,
    ProgramCallFrameEffect,
    ProgramCallStack,
    ProgramCallStackEffect,
)
from .dep import Dep, DepInjectEffect, inject
from .future import Await, FutureAwaitEffect, await_
from .gather import Gather, GatherEffect, gather
from .graph import (
    Annotate,
    CaptureGraph,
    GraphAnnotateEffect,
    GraphCaptureEffect,
    GraphSnapshotEffect,
    GraphStepEffect,
    Snapshot,
    Step,
    graph,
)
from .graph import capture as capture_graph
from .intercept import InterceptEffect, intercept_program_effect
from .io import IO, IOPerformEffect, IOPrintEffect, Print, perform, print_, run
from .memo import MemoGet, MemoGetEffect, MemoPut, MemoPutEffect, memo_get, memo_put
from .pure import Pure, PureEffect
from .reader import Ask, AskEffect, Local, LocalEffect, ask, local
from .result import (
    Catch,
    Fail,
    Finally,
    FirstSuccess,
    Recover,
    ResultCatchEffect,
    ResultFailEffect,
    ResultFinallyEffect,
    ResultFirstSuccessEffect,
    ResultRecoverEffect,
    ResultRetryEffect,
    ResultSafeEffect,
    ResultUnwrapEffect,
    Retry,
    Safe,
    Unwrap,
    catch,
    fail,
    finally_,
    first_success_effect,
    recover,
    retry,
    safe,
    unwrap_result,
)
from .state import (
    Get,
    Modify,
    Put,
    StateGetEffect,
    StateModifyEffect,
    StatePutEffect,
    get,
    modify,
    put,
)
from .spawn import (
    Spawn,
    SpawnBackend,
    SpawnEffect,
    Task,
    TaskJoinEffect,
    spawn,
)
from .thread import Thread, ThreadEffect, ThreadStrategy, thread
from .writer import (
    Listen,
    Log,
    StructuredLog,
    Tell,
    WriterListenEffect,
    WriterTellEffect,
    listen,
    slog,
    tell,
)
from .sim import (
    SimAwait,
    SimAwaitEffect,
    SimTime,
    SimTimeEffect,
    SimulationScheduler,
    handle_sim_await,
    handle_sim_time,
    SIM_SCHEDULER_KEY,
    SIM_TIME_KEY,
)

# Lowercase compatibility aliases
# Functions imported above already provide lowercase helpers

# Legacy lowercase synonyms for backward compatibility
io = IO
step = Step
annotate = Annotate
snapshot = Snapshot
capture = capture_graph


__all__ = [
    "IO",
    "Annotate",
    # Factory helpers
    "Ask",
    "AskEffect",
    "AtomicGet",
    "AtomicGetEffect",
    "AtomicUpdate",
    "AtomicUpdateEffect",
    "Await",
    "CacheGet",
    "CacheGetEffect",
    "CachePut",
    "CachePutEffect",
    # Durable cache effects
    "DurableCacheDelete",
    "DurableCacheExists",
    "DurableCacheGet",
    "DurableCachePut",
    "cachedelete",
    "cacheexists",
    "cacheget",
    "cacheput",
    "ProgramCallFrame",
    "ProgramCallFrameEffect",
    "ProgramCallStack",
    "ProgramCallStackEffect",
    "CaptureGraph",
    "Catch",
    "Dep",
    "DepInjectEffect",
    "Fail",
    "Finally",
    "FirstSuccess",
    "FutureAwaitEffect",
    "Gather",
    "GatherEffect",
    "Get",
    "GraphAnnotateEffect",
    "GraphCaptureEffect",
    "GraphSnapshotEffect",
    "GraphStepEffect",
    "InterceptEffect",
    "IOPerformEffect",
    "IOPrintEffect",
    "Listen",
    "Local",
    "LocalEffect",
    "Log",
    "MemoGet",
    "MemoGetEffect",
    "MemoPut",
    "MemoPutEffect",
    "Modify",
    "Print",
    "Pure",
    # Effect classes
    "PureEffect",
    "Put",
    "Recover",
    "ResultCatchEffect",
    "ResultFailEffect",
    "ResultFinallyEffect",
    "ResultFirstSuccessEffect",
    "ResultRecoverEffect",
    "ResultRetryEffect",
    "ResultSafeEffect",
    "ResultUnwrapEffect",
    "Retry",
    "Safe",
    "Snapshot",
    "StateGetEffect",
    "StateModifyEffect",
    "StatePutEffect",
    "Spawn",
    "SpawnBackend",
    "SpawnEffect",
    "Task",
    "TaskJoinEffect",
    "Step",
    "Thread",
    "ThreadEffect",
    "ThreadStrategy",
    "StructuredLog",
    "Tell",
    "Unwrap",
    "WriterListenEffect",
    "WriterTellEffect",
    "annotate",
    # Compatibility aliases
    "ask",
    "atomic_get",
    "atomic_update",
    "await_",
    "cache_get",
    "cache_put",
    "capture",
    "capture_graph",
    "catch",
    "intercept_program_effect",
    "fail",
    "finally_",
    "first_success_effect",
    "gather",
    "get",
    "graph",
    "inject",
    "io",
    "listen",
    "local",
    "log",
    "memo_get",
    "memo_put",
    "modify",
    "perform",
    "print_",
    "put",
    "recover",
    "retry",
    "thread",
    "run",
    "safe",
    "slog",
    "snapshot",
    "spawn",
    "step",
    "tell",
    "unwrap_result",
    # Simulation effects
    "SimAwait",
    "SimAwaitEffect",
    "SimTime",
    "SimTimeEffect",
    "SimulationScheduler",
    "handle_sim_await",
    "handle_sim_time",
    "SIM_SCHEDULER_KEY",
    "SIM_TIME_KEY",
]
