"""coordinator/protocol/cluster_json.hy の公開面の型(型検査のための宣言 — 実行時は cluster_json.hy を読む・#2760)。

cluster_json.hy は Hy の module なので、pyright は中を読めず、名が全部 Unknown になる。名の規則の読み(naming-from-json)と
task の行の読み(task-record-from-json)を使う使い手(使い手の repo の模擬の世界の検)に、書き手に直せない赤
(Type of "naming_from_json" is unknown ほか)が出る。ここで型を宣言する(store.pyi と同じ形)。

- task-record-from-json は defk(呼ぶと Program を返す)。ほかは素の関数(保存の綴りと読みの部品)。
- 引数と答えの dict は保存の JSON の境界の値(行の形は cluster_json.hy の docstring)。
"""

from typing import Any

from doeff_cluster.coordinator.intent.cluster_model import ClusterNaming, HandoffWatch, TaskRecord

from doeff import Program

MODULE_TAGS: dict[str, str]
RETIRED_NAMING_FIELDS: frozenset[str]

def handoff_watch_from_json(data: dict[str, Any]) -> HandoffWatch: ...
def naming_from_json(text: str) -> ClusterNaming: ...
def task_record_to_json(task: TaskRecord) -> dict[str, Any]: ...
def task_record_from_json(data: dict[str, Any]) -> Program[TaskRecord, Any]: ...
def stored_str(data: dict[str, Any], key: str, default: str | None = None) -> str: ...
def stored_optional_str(data: dict[str, Any], key: str) -> str | None: ...
def stored_int(data: dict[str, Any], key: str, default: int | None = None) -> int: ...
def stored_optional_int(data: dict[str, Any], key: str) -> int | None: ...
def stored_bool(data: dict[str, Any], key: str, default: bool) -> bool: ...
def stored_optional_dict(data: dict[str, Any], key: str) -> dict[str, Any] | None: ...
def stored_items(data: dict[str, Any], key: str) -> tuple[Any, ...]: ...
def old_task_row_reason(old: dict[str, Any] | list[Any] | None, extra: list[str]) -> str | None: ...
