"""coordinator/protocol/store.hy の公開面の型(型検査のための宣言 — 実行時は store.hy を読む・#2446)。

store.hy は Hy の module なので、pyright は中を読めず、名が全部 Unknown になる。調停ループの組を自分で組む使い手(使い手の repo の
模擬の世界の検)が durable-states と wal-store を使うと、書き手に直せない赤(Type of "durable_states" is unknown ほか)が出た。
ここで型を宣言する(request_bodies.pyi と同じ形)。

- Persist は凍った dataclass の EffectBase[None](欄 writes = 変わったキーごとの書き TableWrite — value は新しい値・消えたキーは None・#2722)。
- 置き場は 2 つの形の閉じた和 DurableStore(#2785):
  ByteLog    = file の置き場(foundation/wal_store の WalStore)— byte の I/O だけを持つ。行と写しの形は durable-* の口が綴り・検める。
  DeltaStore = memory の置き場(entry の MemoryWalStore と、それを継いだ模擬の壊れた置き場)— 差分と表をそのまま受け渡す。
- durable-exists・durable-load・durable-persist・durable-checkpoint は置き場の形を切り分けて読み書きする defk(Program を返す)。
- durable-states は handler の値。wal-store と memory-store は置き場を受けて handler を返す関数(handler の型は Any)。
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from doeff import EffectBase, Program
from doeff_hy.table import TableWrite

MODULE_TAGS: dict[str, str]

@dataclass(frozen=True)
class Persist(EffectBase[None]):
    writes: tuple[TableWrite[object], ...]

@runtime_checkable
class ByteLog(Protocol):
    seq: int
    max_log_bytes: int
    snapshot: Path
    log: Path
    def exists(self) -> bool: ...
    def check_place(self) -> None: ...
    def read_snapshot_bytes(self) -> bytes | None: ...
    def read_log_lines(self) -> list[bytes]: ...
    def drop_tail(self, kept: int, size: int, reason: str) -> None: ...
    def append_line(self, line: bytes) -> int: ...
    def write_snapshot(self, data: bytes) -> None: ...
    def table(self) -> dict[str, object]: ...
    def replace_table(self, kv: dict[str, object]) -> None: ...
    def recovery(self) -> dict[str, object] | None: ...

@runtime_checkable
class DeltaStore(Protocol):
    def exists(self) -> bool: ...
    def load(self) -> dict[str, object]: ...
    def persist(self, delta: dict[str, object]) -> None: ...
    def checkpoint(self) -> None: ...
    def table(self) -> dict[str, object]: ...
    def replace_table(self, kv: dict[str, object]) -> None: ...
    def recovery(self) -> dict[str, object] | None: ...

DurableStore = ByteLog | DeltaStore

durable_states: Any

def durable_exists(store: DurableStore) -> Program[bool, Any]: ...
def durable_load(store: DurableStore) -> Program[dict[str, object], Any]: ...
def durable_persist(store: DurableStore, delta: dict[str, object]) -> Program[None, Any]: ...
def durable_checkpoint(store: DurableStore) -> Program[None, Any]: ...
def wal_store(store: DurableStore) -> Any: ...
def memory_store(log: list[dict[str, object]]) -> Any: ...
