from typing import TypeVar

from pinjected import AsyncResolver, Injected, IProxy

from doeff import Program, RunResult

T = TypeVar("T")

def _program_with_dependency_interception(
    prog: Program[T], resolver: AsyncResolver
) -> Program[T]: ...
def program_to_injected(prog: Program[T]) -> Injected[T]: ...
def program_to_iproxy(prog: Program[T]) -> IProxy[T]: ...
def program_to_injected_result(prog: Program[T]) -> Injected[RunResult[T]]: ...
def program_to_iproxy_result(prog: Program[T]) -> IProxy[RunResult[T]]: ...
