"""memory_file.hy の公開面の型(file system の effect の I/O なしの答え手 — 型検査のための宣言・実行時は memory_file.hy を読む・
agora-redesign #2323)。

- memory-file-handler(Python の名 memory_file_handler)は初めの置き場 MemoryFiles を受け、本文の Program に被せる関数を返す
  (defhandler の展開と同じ形: 本文の答えの型をそのまま運ぶ WithHandler)。
- defk は呼ぶと Program を返す(答えの型は Program の 1 つ目の引数)。
- 実装との食い違いは packages/doeff-core-effects/tests/test_hy_module_stubs.py が検める。
"""

from typing import Any, Protocol, TypeVar

from doeff_vm import WithHandler

from doeff import Program
from doeff_core_effects.file_effects import (
    DirEntry,
    FileFailed,
    MemoryFiles,
    PathKind,
    PathStat,
    SourceNotCompiled,
)

_A = TypeVar("_A")

ROOT: str
NO_ENTRY: str
NOT_DIRECTORY: str
IS_DIRECTORY: str
EXISTS: str
NOT_EMPTY: str
INVALID: str
NOT_PERMITTED: str

def refused(reason: str, path: str) -> Program[FileFailed, Any]: ...
def refused_move(reason: str, source: str, target: str) -> Program[FileFailed, Any]: ...
def normal(path: str) -> Program[str, Any]: ...
def kind_in(store: MemoryFiles, path: str) -> Program[PathKind, Any]: ...
def parent_refusal(store: MemoryFiles, path: str) -> Program[FileFailed | None, Any]: ...
def with_dirs(store: MemoryFiles, path: str) -> Program[MemoryFiles | FileFailed, Any]: ...
def with_file(
    store: MemoryFiles, path: str, content: bytes, mode: int | None
) -> Program[MemoryFiles | FileFailed, Any]: ...
def link_in(
    store: MemoryFiles, source: str, target: str
) -> Program[MemoryFiles | FileFailed, Any]: ...
def compile_in_store(
    store: MemoryFiles, tree: str, items: tuple[tuple[str, str], ...]
) -> Program[tuple[MemoryFiles, tuple[SourceNotCompiled, ...]], Any]: ...
def content_of(store: MemoryFiles, path: str) -> Program[bytes | FileFailed, Any]: ...
def dir_refusal(store: MemoryFiles, path: str) -> Program[FileFailed | None, Any]: ...
def entries_below(store: MemoryFiles, path: str) -> Program[tuple[DirEntry, ...], Any]: ...
def list_in(store: MemoryFiles, path: str) -> Program[tuple[DirEntry, ...] | FileFailed, Any]: ...
def without_tree(store: MemoryFiles, path: str) -> Program[MemoryFiles, Any]: ...
def remove_in(store: MemoryFiles, path: str) -> Program[MemoryFiles | FileFailed, Any]: ...
def copy_tree_in(
    store: MemoryFiles, source: str, target: str
) -> Program[MemoryFiles | FileFailed, Any]: ...
def moved(path: str, source: str, target: str) -> Program[str, Any]: ...
def rename_in(
    store: MemoryFiles, source: str, target: str
) -> Program[MemoryFiles | FileFailed, Any]: ...
def return_path(path: str) -> Program[str, Any]: ...
def stat_in(store: MemoryFiles, path: str) -> Program[PathStat, Any]: ...

class _MemoryFileHandler(Protocol):
    """本文の Program に handler を被せる関数(答えの型は本文のまま)。"""

    def __call__(self, body: Program[_A, object], /) -> WithHandler[_A]: ...

def memory_file_handler(initial: MemoryFiles) -> _MemoryFileHandler: ...
def return_store(store: MemoryFiles) -> Program[MemoryFiles, Any]: ...
