"""os_file.hy の公開面の型(file system の effect の本物の答え手 — 型検査のための宣言・実行時は os_file.hy を読む)。

- os-file-handler(Python の名 os_file_handler)は引数の無い defhandler — 値そのものが本文の Program に被せる関数
  (defhandler の展開と同じ形: 本文の答えの型をそのまま運ぶ WithHandler)。
- defk は呼ぶと Program を返す(答えの型は Program の 1 つ目の引数)。
- 実装との食い違いは packages/doeff-core-effects/tests/test_hy_module_stubs.py が検める。
"""

from collections.abc import Callable
from typing import Any, Protocol, TypeVar

from doeff_vm import WithHandler

from doeff import Program
from doeff_core_effects.file_effects import DirEntry, DiskUsage, FileFailed, LockHeld, PathKind, PathStat

_A = TypeVar("_A")

def failed(path: str, error: OSError) -> Program[FileFailed, Any]: ...
def kind_of_mode(mode: int) -> Program[PathKind, Any]: ...
def stat_path(path: str, follow_symlinks: bool) -> Program[PathStat | FileFailed, Any]: ...
def write_content(
    path: str, content: str | bytes, mode: int | None, replace: bool, sync: bool
) -> Program[FileFailed | None, Any]: ...
def make_directory(path: str, mode: int | None) -> Program[FileFailed | None, Any]: ...
def entry_of(path: str, name: str) -> Program[DirEntry, Any]: ...
def list_directory(path: str) -> Program[tuple[DirEntry, ...] | FileFailed, Any]: ...
def walk_tree(path: str) -> Program[tuple[DirEntry, ...] | FileFailed, Any]: ...
def remove_tree(path: str) -> Program[FileFailed | None, Any]: ...
def acquire_lock(path: str) -> Program[LockHeld | FileFailed, Any]: ...
def guarded(path: str, action: Callable[[], object]) -> Program[FileFailed | None, Any]: ...
def read_file(path: str, binary: bool, limit: int | None) -> Program[str | bytes | FileFailed, Any]: ...
def disk_free(path: str) -> Program[int | FileFailed, Any]: ...
def disk_usage(path: str) -> Program[DiskUsage | FileFailed, Any]: ...
def measure_tree(path: str) -> Program[int | FileFailed, Any]: ...

class _OsFileHandler(Protocol):
    """本文の Program に handler を被せる関数(答えの型は本文のまま)。"""

    def __call__(self, body: Program[_A, object], /) -> WithHandler[_A]: ...

os_file_handler: _OsFileHandler
