"""
CESK Machine package for the doeff effect interpreter.

This package implements a CESK machine (Control, Environment, Store, Kontinuation)
as described in Felleisen & Friedman (1986) and Van Horn & Might (2010).

The unified multi-task architecture supports:
- Multiple concurrent tasks with shared Store
- TaskId, FutureId, SpawnId for coordination
- TaskStatus (Ready, Blocked, Requesting, Done) for task state
- Condition types for blocking conditions
- Request types for runtime operations

For full documentation, see SPEC-CORE-001.
"""

from doeff.cesk.classification import (
    find_intercept_frame_index,
    has_intercept_frame,
    is_control_flow_effect,
    is_effectful,
    is_pure_effect,
)
from doeff.cesk.errors import (
    HandlerRegistryError,
    InterpreterInvariantError,
    UnhandledEffectError,
)
from doeff.cesk.frames import (
    ContinueError,
    ContinueGenerator,
    ContinueProgram,
    ContinueValue,
    Frame,
    FrameResult,
    GatherFrame,
    InterceptBypassFrame,
    InterceptFrame,
    Kontinuation,
    ListenFrame,
    LocalFrame,
    RaceFrame,
    ReturnFrame,
    SafeFrame,
)
from doeff.cesk.handlers import Handler, HandlerContext
from doeff.cesk.helpers import (
    _merge_thread_state,
    apply_intercept_chain,
    apply_transforms,
    merge_store,
    shutdown_shared_executor,
    to_generator,
)
from doeff.cesk.kontinuation import (
    continuation_depth,
    find_frame,
    find_safe_frame_index,
    get_intercept_transforms,
    has_frame,
    has_safe_frame,
    pop_frame,
    push_frame,
    split_at_safe,
    unwind_error,
    unwind_value,
)
from doeff.cesk.result import (
    CESKResult,
    Done,
    Failed,
    PythonAsyncSyntaxEscape,
    StepResult,
    Suspended,
    Terminal,
)
from doeff.cesk.runner import AsyncRunner, SyncRunner
from doeff.cesk.runtime import AsyncRuntime, BaseRuntime, SimulationRuntime, SyncRuntime
from doeff.cesk.runtime_result import (
    EffectCallNode,
    EffectStackTrace,
    KFrame,
    KStackTrace,
    PythonFrame,
    PythonStackTrace,
    RuntimeResult,
    RuntimeResultImpl,
    SourceLocation,
)
from doeff.cesk.state import (
    AwaitExternal,
    Blocked,
    CESKState,
    Condition,
    Control,
    CreateFuture,
    CreateSpawn,
    CreateTask,
    EffectControl,
    Error,
    FutureCondition,
    PerformIO,
    ProgramControl,
    Ready,
    Request,
    Requesting,
    ResolveFuture,
    SpawnCondition,
    TaskCondition,
    TaskState,
    TaskStatus,
    TimeCondition,
    Value,
)
from doeff.cesk.state import (
    Done as TaskDone,
)
from doeff.cesk.step import step
from doeff.cesk.types import (
    Environment,
    FutureHandle,
    FutureId,
    SpawnHandle,
    SpawnId,
    Store,
    TaskHandle,
    TaskId,
    empty_environment,
    empty_store,
)


__all__ = [
    "AsyncRunner",
    "AsyncRuntime",
    "AwaitExternal",
    "BaseRuntime",
    "Blocked",
    "CESKResult",
    "CESKState",
    "Condition",
    "ContinueError",
    "ContinueGenerator",
    "ContinueProgram",
    "ContinueValue",
    "Control",
    "CreateFuture",
    "CreateSpawn",
    "CreateTask",
    "Done",
    "EffectCallNode",
    "EffectControl",
    "EffectStackTrace",
    "Environment",
    "Error",
    "Failed",
    "Frame",
    "FrameResult",
    "FutureCondition",
    "FutureHandle",
    "FutureId",
    "GatherFrame",
    "Handler",
    "HandlerContext",
    "HandlerRegistryError",
    "InterceptBypassFrame",
    "InterceptFrame",
    "InterpreterInvariantError",
    "KFrame",
    "KStackTrace",
    "Kontinuation",
    "ListenFrame",
    "LocalFrame",
    "PerformIO",
    "ProgramControl",
    "PythonFrame",
    "PythonStackTrace",
    "RaceFrame",
    "Ready",
    "Request",
    "Requesting",
    "ResolveFuture",
    "ReturnFrame",
    "RuntimeResult",
    "RuntimeResultImpl",
    "SafeFrame",
    "SimulationRuntime",
    "SourceLocation",
    "SpawnCondition",
    "SpawnHandle",
    "SpawnId",
    "StepResult",
    "Store",
    "Suspended",
    "PythonAsyncSyntaxEscape",
    "SyncRunner",
    "SyncRuntime",
    "TaskCondition",
    "TaskDone",
    "TaskHandle",
    "TaskId",
    "TaskState",
    "TaskStatus",
    "Terminal",
    "TimeCondition",
    "UnhandledEffectError",
    "Value",
    "_merge_thread_state",
    "apply_intercept_chain",
    "apply_transforms",
    "continuation_depth",
    "empty_environment",
    "empty_store",
    "find_frame",
    "find_intercept_frame_index",
    "find_safe_frame_index",
    "get_intercept_transforms",
    "has_frame",
    "has_intercept_frame",
    "has_safe_frame",
    "is_control_flow_effect",
    "is_effectful",
    "is_pure_effect",
    "merge_store",
    "pop_frame",
    "push_frame",
    "shutdown_shared_executor",
    "split_at_safe",
    "step",
    "to_generator",
    "unwind_error",
    "unwind_value",
]
