"""runtime_env_rules.hy の公開面の型(型検査のための宣言 — 実行時は runtime_env_rules.hy を読む)。

runtime_env_rules.hy は Hy の module なので、pyright は中を読めない(runtime_env_model.pyi と同じ理由・同じ形)。型そのものは
doeff_cluster.shared.intent.runtime_env_model.pyi。
- defk(env-failure・root-split・url-location・project-material・key-material・env-key・native-key・runtime-env->json・
  project-of-json・runtime-env-of-json)は呼ぶと Program を返す。
  defn(child-environ-refusal)は普通の関数。`runtime-env->json` の Python の名は Hy の mangle の形。
"""

from typing import Any

from doeff import Program
from doeff_hy.json_value import JsonValue

from doeff_cluster.shared.intent.runtime_env_model import EnvFailure, EnvFailureKind, NativeWheel, PythonProject, RepoLocation, RuntimeEnv

def child_environ_refusal(environ: object) -> str | None: ...
def env_failure(kind: EnvFailureKind, detail: str) -> Program[EnvFailure, Any]: ...
def root_split(root: str) -> Program[tuple[str, str], Any]: ...
def url_location(url: str) -> Program[RepoLocation, Any]: ...
def project_material(project: PythonProject) -> Program[dict[str, JsonValue], Any]: ...
def key_material(env: RuntimeEnv, platform: str) -> Program[dict[str, JsonValue], Any]: ...
def env_key(env: RuntimeEnv, platform: str) -> Program[str, Any]: ...
def native_key(wheel: NativeWheel, tree_hashes: tuple[str, ...], python: str, platform: str) -> Program[str, Any]: ...
def hyx_runtime_env_XgreaterHthan_signXjson(env: RuntimeEnv) -> Program[dict[str, JsonValue], Any]: ...
def project_of_json(value: dict[str, JsonValue]) -> Program[PythonProject, Any]: ...
def runtime_env_of_json(value: dict[str, JsonValue]) -> Program[RuntimeEnv, Any]: ...
