from __future__ import annotations

from typing import Any, Protocol

from doeff.program import Program

class InterpreterDiscovery(Protocol):
    def find_default_interpreter(self, program_path: str) -> str | None: ...
    def validate_interpreter(self, func: Any) -> bool: ...

class EnvDiscovery(Protocol):
    def discover_default_envs(self, program_path: str) -> list[str]: ...

class EnvMerger(Protocol):
    def merge_envs(self, env_sources: list[str]) -> Program[dict]: ...

class SymbolLoader(Protocol):
    def load_symbol(self, full_path: str) -> Any: ...

class IndexerBasedDiscovery:
    indexer_class: Any
    symbol_loader: SymbolLoader

    def __init__(self, symbol_loader: SymbolLoader | None = ...) -> None: ...
    def find_default_interpreter(self, program_path: str) -> str | None: ...
    def discover_default_envs(self, program_path: str) -> list[str]: ...
    def validate_interpreter(self, func: Any) -> bool: ...
    def _extract_module_path(self, full_path: str) -> str: ...
    def _get_module_hierarchy(self, module_path: str) -> list[str]: ...

class StandardEnvMerger:
    symbol_loader: SymbolLoader

    def __init__(self, symbol_loader: SymbolLoader | None = ...) -> None: ...
    def merge_envs(self, env_sources: list[str]) -> Program[dict]: ...

class StandardSymbolLoader:
    def load_symbol(self, full_path: str) -> Any: ...
