class SymbolLoader:
    def load_symbol(self, full_path: str) -> Any: ...

class StandardEnvMerger:
    def __init__(self, symbol_loader: SymbolLoader | None = ...) -> Any: ...
    def merge_envs(self, env_sources: list[str]) -> Program[dict]: ...

class EnvDiscovery:
    def discover_default_envs(self, program_path: str) -> list[str]: ...

class EnvMerger:
    def merge_envs(self, env_sources: list[str]) -> Program[dict]: ...

class IndexerBasedDiscovery:
    def __init__(self, symbol_loader: SymbolLoader | None = ...) -> Any: ...
    def find_default_interpreter(self, program_path: str) -> str | None: ...
    def discover_default_envs(self, program_path: str) -> list[str]: ...
    def validate_interpreter(self, func: Any) -> bool: ...
    def _extract_module_path(self, full_path: str) -> str: ...
    def _get_module_hierarchy(self, module_path: str) -> list[str]: ...

class StandardSymbolLoader:
    def load_symbol(self, full_path: str) -> Any: ...

class InterpreterDiscovery:
    def find_default_interpreter(self, program_path: str) -> str | None: ...
    def validate_interpreter(self, func: Any) -> bool: ...

