"""
Core module for the doeff system.

This module re-exports the main components for backwards compatibility
and convenience. All implementations have been moved to their respective modules.
"""

from doeff.do import do
from doeff.effects import (
    IO,
    Annotate,
    # Capitalized aliases
    Ask,
    Await,
    Dep,
    Fail,
    Gather,
    Get,
    Listen,
    Local,
    Log,
    MemoGet,
    MemoPut,
    Modify,
    Print,
    Put,
    Safe,
    Snapshot,
    Step,
    Tell,
    annotate,
    # Lowercase compatibility
    ask,
    await_,
    fail,
    get,
    io,
    listen,
    local,
    memo_get,
    memo_put,
    modify,
    print_,
    put,
    safe,
    step,
    tell,
)
from doeff.kleisli import KleisliProgram
from doeff.program import Program
from doeff.types import Effect, ExecutionContext, ListenResult, RunResult

__all__ = [
    "IO",
    "Annotate",
    "Ask",
    "Await",
    "Dep",
    "Effect",
    "ExecutionContext",
    "Fail",
    "Gather",
    "Get",
    "KleisliProgram",
    "Listen",
    "ListenResult",
    "Local",
    "Log",
    "MemoGet",
    "MemoPut",
    "Modify",
    "Print",
    "Program",
    "Put",
    "RunResult",
    "Safe",
    "Snapshot",
    "Step",
    "Tell",
    "annotate",
    "ask",
    "await_",
    "do",
    "fail",
    "get",
    "io",
    "listen",
    "local",
    "memo_get",
    "memo_put",
    "modify",
    "print_",
    "put",
    "safe",
    "step",
    "tell",
]
