# interpreters.hy(Hy)の型の宣言 — conftest.py と検の file が読む口だけ(Hy の module は型検査器が読めない)。
from collections.abc import Callable
from typing import Protocol

from doeff import Program
from doeff_core_effects.postgres_sql import PostgresConnections

class BuiltInterpreter:
    run: Callable[[Program], object]
    def close(self) -> None: ...
    def harness(self) -> object: ...

PG_DSN_VARIABLE: str
DATABASE: str
ORIGIN_HOST: str

class LawSetup: ...

class PgConnection(Protocol):
    autocommit: bool
    def close(self) -> None: ...

def open_postgres() -> PgConnection: ...
def postgres_connections(size: int = 4) -> PostgresConnections: ...
def fresh_prefix() -> str: ...
def run_sql(connections: PostgresConnections, program: Program) -> object: ...
def prepared_store(connections: PostgresConnections, prefix: str) -> object: ...
def records_handler_for(store: object) -> Callable[[str], object]: ...
def skip_reason(name: str) -> str: ...
def build_interpreter(name: str) -> BuiltInterpreter: ...

LAW_TOKENS: dict[str, str]
