# interpreters.hy(Hy)の型の宣言 — conftest.py が読む口だけ(Hy の module は型検査器が読めない)。
from collections.abc import Callable
from typing import Protocol

from doeff import Program

class BuiltInterpreter:
    run: Callable[[Program], object]
    def close(self) -> None: ...
    def harness(self) -> object: ...

PG_DSN_VARIABLE: str

class LawSetup: ...

class PgConnection(Protocol):
    autocommit: bool
    def close(self) -> None: ...

def open_postgres() -> PgConnection: ...
def skip_reason(name: str) -> str: ...
def build_interpreter(name: str) -> BuiltInterpreter: ...
